//
//  NewTaskView.swift
//  LifeTrack
//
//  Created by Halalisani Mbanjwa on 2026/04/18.
//

import SwiftData
import SwiftUI
import UniformTypeIdentifiers
import VisionKit

struct NewTaskView: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext
    @Query(sort: \CustomTaskCategory.title) private var customCategories: [CustomTaskCategory]

    @StateObject private var voiceInput = VoiceTaskInputManager()
    @StateObject private var voiceEnhancer = AIVoiceTaskEnhancer()

    private let existingTask: LifeTask?
    private let originalDocumentStorageName: String?
    private let autoStartVoice: Bool
    private let isFreshNewTask: Bool
    @State private var didAutoStartVoice = false
    @State private var isShowingResumePrompt = false
    @State private var pendingDraft: NewTaskDraft?
    @State private var didOfferDraftResume = false

    @State private var title: String
    @State private var categoryRawValue: String
    @State private var dueDate: Date
    @State private var isCompleted: Bool
    @State private var notes: String
    @State private var templateAction: TaskTemplateAction
    @State private var priority: TaskPriority
    @State private var recurrence: TaskRecurrence
    @State private var durationMinutes: Int
    @State private var documentStorageName: String?
    @State private var documentDisplayName: String?
    @State private var documentExtractedText: String
    @State private var documentAnalysisSummary: String?
    @State private var documentSuggestedTitle: String?
    @State private var documentSuggestedDueDate: Date?
    @State private var documentKeywords: [String]
    @State private var isImportingDocument = false
    @State private var isScanningDocument = false
    @State private var isAnalyzingDocument = false
    @State private var isShowingCategoryManager = false
    @State private var activeDueDatePicker: DueDatePickerMode?
    @State private var pendingCategoryOption: TaskCategoryOption?
    @State private var documentError: String?
    @State private var didSave = false
    @State private var voiceTranscript = ""
    @State private var lastVoiceGeneratedTitle = ""
    @State private var lastVoiceGeneratedNotes = ""
    @State private var didApplyVoiceCategory = false
    @State private var didApplyVoiceDueDate = false
    @State private var didApplyDocumentSuggestion = false
    @State private var documentScrollRequest: UUID?
    @State private var lastAutoGeneratedDocumentNotes = ""
    @State private var locationConfig: LocationReminderConfig?
    @State private var isShowingLocationPicker = false
    @State private var isAIEnhancing = false
    @State private var isShowingVoiceTranscriptDisclosure = false
    @AppStorage(LifeTrackSettings.Keys.voiceTranscriptDisclosureShown) private var voiceTranscriptDisclosureShown = false
    @State private var advancedFieldValues: [String: String] = [:]
    @State private var isAdvancedExpanded = false
    @State private var financialEnabled = false
    @State private var financialType: TaskFinancialType = .expense
    @State private var plannedAmountText = ""
    @State private var actualAmountText = ""
    @State private var currencyCode = MoneyCurrency.defaultCode
    @State private var budgetCategory = ""
    @State private var hasPaymentDate = false
    @State private var paymentDate = Date()
    @State private var financialLinkOption: MoneyLinkOption = .none
    @State private var financialNotes = ""
    @State private var includeInMonthlySpending = true
    @State private var markPlannedOnCreate = false
    @EnvironmentObject private var subscriptionManager: SubscriptionManager

    private let durationOptions = [15, 30, 45, 60, 90, 120]
    private static var currentMoneyCurrencyCode: String {
        MoneyCurrency.normalized(UserDefaults.standard.string(forKey: LifeTrackSettings.Keys.moneyCurrencyCode) ?? MoneyCurrency.defaultCode)
    }

    init(task: LifeTask? = nil, template: TaskTemplate? = nil, captureDraft: CapturedTaskDraft? = nil, autoStartVoice: Bool = false) {
        existingTask = task
        originalDocumentStorageName = task?.documentStorageName
        self.autoStartVoice = autoStartVoice
        self.isFreshNewTask = (task == nil && template == nil && captureDraft == nil)

        let captureDraft = captureDraft
        let structuredCaptureDraft = captureDraft?.structuredDraft
        let captureCategoryRawValue = structuredCaptureDraft?.category?.rawValue ?? captureDraft?.resolvedCategory.rawValue
        let captureDueDate = structuredCaptureDraft?.dueDate ?? captureDraft?.resolvedDueDate
        let capturePriority = structuredCaptureDraft?.priority ?? captureDraft?.resolvedPriority
        let captureAdvancedFields = structuredCaptureDraft?.advancedFields ?? [:]
        let captureFinancialEnabled =
            structuredCaptureDraft?.financialEnabled == true ||
            structuredCaptureDraft?.financialType != nil ||
            structuredCaptureDraft?.plannedAmount != nil ||
            structuredCaptureDraft?.actualAmount != nil ||
            structuredCaptureDraft?.budgetCategory != nil ||
            structuredCaptureDraft?.paymentDate != nil
        let templateWantsFinance = template?.id == "bill"

        let template = template
        _title = State(initialValue: task?.title ?? captureDraft?.resolvedTitle ?? template?.title ?? "")
        _categoryRawValue = State(initialValue: task?.categoryRawValue ?? captureCategoryRawValue ?? template?.category.rawValue ?? TaskCategory.personal.rawValue)
        _dueDate = State(initialValue: task?.dueDate ?? captureDueDate ?? template?.dueDate ?? Date())
        _isCompleted = State(initialValue: task?.isCompleted ?? false)
        _notes = State(initialValue: task?.notes ?? captureDraft?.resolvedNotes ?? template?.notes ?? "")
        _templateAction = State(initialValue: task?.templateAction ?? template?.action ?? .none)
        _priority = State(initialValue: task?.priority ?? capturePriority ?? template?.priority ?? .normal)
        _recurrence = State(initialValue: task?.recurrence ?? template?.recurrence ?? .none)
        _durationMinutes = State(initialValue: task?.scheduledDurationMinutes ?? template?.estimatedDurationMinutes ?? 30)
        _documentStorageName = State(initialValue: task?.documentStorageName)
        _documentDisplayName = State(initialValue: task?.documentDisplayName)
        _documentExtractedText = State(initialValue: task?.documentExtractedText ?? "")
        _documentAnalysisSummary = State(initialValue: task?.documentAnalysisSummary)
        _documentSuggestedTitle = State(initialValue: task?.documentSuggestedTitle)
        _documentSuggestedDueDate = State(initialValue: task?.documentSuggestedDueDate)
        _documentKeywords = State(initialValue: task?.documentKeywords ?? [])
        if let lat = task?.locationReminderLatitude, let lon = task?.locationReminderLongitude {
            _locationConfig = State(initialValue: LocationReminderConfig(
                name: task?.locationReminderName ?? "",
                latitude: lat,
                longitude: lon,
                radius: task?.locationReminderRadius ?? 150,
                onArrival: task?.locationReminderOnArrival ?? true
            ))
        }
        _advancedFieldValues = State(initialValue: task?.advancedFields ?? captureAdvancedFields)
        _isAdvancedExpanded = State(initialValue: !(task?.advancedFields.isEmpty ?? captureAdvancedFields.isEmpty))
        _financialEnabled = State(initialValue: task?.financialEnabled ?? (captureFinancialEnabled || templateWantsFinance))
        _financialType = State(initialValue: task?.financialType ?? structuredCaptureDraft?.financialType ?? .expense)
        _plannedAmountText = State(initialValue: Self.amountInputString(task?.plannedAmount ?? structuredCaptureDraft?.plannedAmount))
        _actualAmountText = State(initialValue: Self.amountInputString(task?.actualAmount ?? structuredCaptureDraft?.actualAmount))
        _currencyCode = State(initialValue: task?.currencyCode ?? structuredCaptureDraft?.currencyCode ?? Self.currentMoneyCurrencyCode)
        _budgetCategory = State(initialValue: task?.budgetCategory ?? structuredCaptureDraft?.budgetCategory ?? (templateWantsFinance ? "Bills" : ""))
        _hasPaymentDate = State(initialValue: task?.paymentDate != nil || structuredCaptureDraft?.paymentDate != nil)
        _paymentDate = State(initialValue: task?.paymentDate ?? structuredCaptureDraft?.paymentDate ?? task?.dueDate ?? captureDueDate ?? template?.dueDate ?? Date())
        _financialLinkOption = State(initialValue: MoneyLinkOption.resolved(
            budgetId: task?.linkedBudgetId ?? structuredCaptureDraft?.linkedBudgetId,
            goalId: task?.linkedGoalId ?? structuredCaptureDraft?.linkedGoalId
        ))
        _financialNotes = State(initialValue: task?.financialNotes ?? structuredCaptureDraft?.financialNotes ?? "")
        _includeInMonthlySpending = State(initialValue: task?.includeInMonthlySpending ?? structuredCaptureDraft?.includeInMonthlySpending ?? true)
        _markPlannedOnCreate = State(initialValue: task?.markPlannedOnCreate ?? structuredCaptureDraft?.markPlannedOnCreate ?? templateWantsFinance)
        _voiceTranscript = State(initialValue: captureDraft?.rawText ?? "")
    }

    var body: some View {
        NavigationStack {
            ZStack {
                LifeTrackTheme.appBackground
                    .ignoresSafeArea()

                ScrollViewReader { scrollProxy in
                    ScrollView {
                        VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.large) {
                            header

                            voiceCard
                                .id(NewTaskViewAnchor.voiceCard)

                            taskCard
                                .id(NewTaskViewAnchor.taskCard)

                            planningCard

                            dateCard

                            financialDetailsCard

                            if subscriptionManager.tier >= .standard {
                                locationCard
                            }

                            notesCard

                            advancedFieldsCard

                            documentCard

                        if templateAction == .email {
                            templateActionCard
                        }

                        if existingTask != nil {
                            statusCard
                        }
                    }
                        .padding(.horizontal, LifeTrackTheme.Spacing.xLarge)
                        .padding(.top, LifeTrackTheme.Spacing.medium)
                        .padding(.bottom, 112)
                    }
                    .scrollIndicators(.hidden)
                    .onChange(of: documentScrollRequest) { _, newValue in
                        guard newValue != nil else { return }
                        withAnimation(.easeOut(duration: 0.28)) {
                            scrollProxy.scrollTo(NewTaskViewAnchor.taskCard, anchor: .top)
                        }
                        documentScrollRequest = nil
                    }
                    .overlay(alignment: .bottomTrailing) {
                        VoiceFloatingButton(isRecording: voiceInput.isRecording) {
                            handleFloatingVoiceButtonTap(scrollProxy: scrollProxy)
                        }
                        .padding(.trailing, LifeTrackTheme.Spacing.xLarge)
                        .padding(.bottom, LifeTrackTheme.Spacing.xxLarge)
                    }
                }
            }
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button("Save", action: save)
                        .fontWeight(.semibold)
                        .disabled(!canSave)
                }
            }
            .fileImporter(
                isPresented: $isImportingDocument,
                allowedContentTypes: [.item],
                allowsMultipleSelection: false,
                onCompletion: handleDocumentImport
            )
            .fullScreenCover(isPresented: $isScanningDocument) {
                DocumentScannerView { result in
                    isScanningDocument = false
                    handleScanResult(result)
                }
                .ignoresSafeArea()
            }
            .sheet(isPresented: $isShowingLocationPicker) {
                LocationPickerView { config in
                    locationConfig = config
                }
                .presentationDetents([.large])
                .presentationDragIndicator(.visible)
            }
            .sheet(isPresented: $isShowingCategoryManager) {
                CategoryManagerView { option in
                    categoryRawValue = option.id
                    pendingCategoryOption = option
                }
                .presentationDetents([.large])
                .presentationDragIndicator(.visible)
            }
            .sheet(item: $activeDueDatePicker) { mode in
                DueDatePickerSheet(mode: mode, dueDate: $dueDate)
                    .presentationDetents([mode.presentationDetent])
                    .presentationDragIndicator(.visible)
                    .presentationBackground(LifeTrackTheme.ColorPalette.backgroundBottom)
            }
            .onDisappear {
                voiceInput.stopRecording()

                if !didSave && documentStorageName != originalDocumentStorageName {
                    DocumentStore.delete(storageName: documentStorageName)
                }

                if isFreshNewTask && !didSave {
                    persistDraftIfMeaningful()
                }
            }
            .onChange(of: voiceInput.transcript) { _, newTranscript in
                voiceTranscript = newTranscript
                applyVoiceTranscript(newTranscript)
            }
            .onChange(of: dueDate) { _, newDueDate in
                if !hasPaymentDate {
                    paymentDate = newDueDate
                }
            }
            .onChange(of: voiceInput.isRecording) { wasRecording, isNowRecording in
                if wasRecording && !isNowRecording,
                   !voiceTranscript.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                   subscriptionManager.tier >= .ultimate,
                   voiceEnhancer.isConfigured {
                    Task { await enhanceVoiceDraftWithAI() }
                }
            }
            .onAppear {
                if autoStartVoice && !didAutoStartVoice {
                    didAutoStartVoice = true
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.35) {
                        if !voiceInput.isRecording {
                            voiceInput.toggleRecording()
                        }
                    }
                }

                if isFreshNewTask && !didOfferDraftResume,
                   let draft = NewTaskDraftStore.load() {
                    didOfferDraftResume = true
                    pendingDraft = draft
                    isShowingResumePrompt = true
                }
            }
            .confirmationDialog(
                "Resume previous task?",
                isPresented: $isShowingResumePrompt,
                titleVisibility: .visible,
                presenting: pendingDraft
            ) { draft in
                Button("Resume") {
                    apply(draft: draft)
                    pendingDraft = nil
                }
                Button("Discard", role: .destructive) {
                    NewTaskDraftStore.clear()
                    pendingDraft = nil
                }
                Button("Keep Editing Later", role: .cancel) {
                    pendingDraft = nil
                }
            } message: { draft in
                Text(resumePromptMessage(for: draft))
            }
            .alert("Send voice note to AI?", isPresented: $isShowingVoiceTranscriptDisclosure) {
                Button("Not now", role: .cancel) { }
                Button("Allow") {
                    voiceTranscriptDisclosureShown = true
                    Task { await enhanceVoiceDraftWithAI() }
                }
            } message: {
                Text("To turn your voice note into a structured task, the transcript is sent to Anthropic's Claude API. Avoid speaking sensitive details (full names, addresses, ID numbers, medical info) you don't want to leave the device.")
            }
        }
    }

    private func resumePromptMessage(for draft: NewTaskDraft) -> String {
        let title = draft.title.trimmingCharacters(in: .whitespacesAndNewlines)
        let preview: String
        if !title.isEmpty {
            preview = "\"\(title)\""
        } else if !draft.voiceTranscript.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            preview = "your voice note"
        } else {
            preview = "your unfinished task"
        }
        let relative = draft.savedAt.formatted(.relative(presentation: .named))
        return "You have an unsaved task (\(preview)) from \(relative). Pick up where you left off?"
    }

    private func sanitizedAdvancedFields() -> [String: String] {
        let allowedKeys = Set(selectedCategory.advancedFields.map(\.rawValue))
        var result: [String: String] = [:]
        for (key, value) in advancedFieldValues where allowedKeys.contains(key) {
            let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty { result[key] = trimmed }
        }
        return result
    }

    private func currentDraftSnapshot() -> NewTaskDraft {
        NewTaskDraft(
            title: title,
            notes: notes,
            categoryRawValue: categoryRawValue,
            dueDate: dueDate,
            priorityRawValue: priority.rawValue,
            recurrenceRawValue: recurrence.rawValue,
            templateActionRawValue: templateAction.rawValue,
            durationMinutes: durationMinutes,
            voiceTranscript: voiceTranscript,
            locationName: locationConfig?.name,
            locationLatitude: locationConfig?.latitude,
            locationLongitude: locationConfig?.longitude,
            locationRadius: locationConfig?.radius,
            locationOnArrival: locationConfig?.onArrival,
            advancedFields: sanitizedAdvancedFields(),
            financialEnabled: financialEnabled,
            financialTypeRawValue: financialType.rawValue,
            plannedAmountText: plannedAmountText,
            actualAmountText: actualAmountText,
            currencyCode: currencyCode,
            budgetCategory: budgetCategory,
            hasPaymentDate: hasPaymentDate,
            paymentDate: hasPaymentDate ? paymentDate : nil,
            financialLinkRawValue: financialLinkOption.rawValue,
            financialNotes: financialNotes,
            includeInMonthlySpending: includeInMonthlySpending,
            markPlannedOnCreate: markPlannedOnCreate,
            savedAt: Date()
        )
    }

    private func draftHasContent() -> Bool {
        if !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return true }
        if !notes.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return true }
        if !voiceTranscript.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return true }
        if locationConfig != nil { return true }
        if priority != .normal { return true }
        if recurrence != .none { return true }
        if !sanitizedAdvancedFields().isEmpty { return true }
        if financialEnabled { return true }
        return false
    }

    private func persistDraftIfMeaningful() {
        guard draftHasContent() else {
            NewTaskDraftStore.clear()
            return
        }
        NewTaskDraftStore.save(currentDraftSnapshot())
    }

    private func apply(draft: NewTaskDraft) {
        title = draft.title
        notes = draft.notes
        categoryRawValue = draft.categoryRawValue
        dueDate = draft.dueDate
        priority = TaskPriority(rawValue: draft.priorityRawValue) ?? .normal
        recurrence = TaskRecurrence(rawValue: draft.recurrenceRawValue) ?? .none
        templateAction = TaskTemplateAction(rawValue: draft.templateActionRawValue) ?? .none
        durationMinutes = draft.durationMinutes
        voiceTranscript = draft.voiceTranscript
        if let name = draft.locationName,
           let lat = draft.locationLatitude,
           let lon = draft.locationLongitude {
            locationConfig = LocationReminderConfig(
                name: name,
                latitude: lat,
                longitude: lon,
                radius: draft.locationRadius ?? 150,
                onArrival: draft.locationOnArrival ?? true
            )
        }
        advancedFieldValues = draft.advancedFields
        isAdvancedExpanded = !draft.advancedFields.isEmpty
        financialEnabled = draft.financialEnabled ?? false
        financialType = TaskFinancialType(rawValue: draft.financialTypeRawValue ?? "") ?? .expense
        plannedAmountText = draft.plannedAmountText ?? ""
        actualAmountText = draft.actualAmountText ?? ""
        currencyCode = MoneyCurrency.normalized(draft.currencyCode ?? MoneyCurrency.defaultCode)
        budgetCategory = draft.budgetCategory ?? ""
        hasPaymentDate = draft.hasPaymentDate ?? false
        paymentDate = draft.paymentDate ?? dueDate
        financialLinkOption = MoneyLinkOption(rawValue: draft.financialLinkRawValue ?? "") ?? .none
        financialNotes = draft.financialNotes ?? ""
        includeInMonthlySpending = draft.includeInMonthlySpending ?? true
        markPlannedOnCreate = draft.markPlannedOnCreate ?? false
    }

    private var header: some View {
        HStack(alignment: .firstTextBaseline, spacing: 6) {
            Text(existingTask == nil ? "New Task" : "Edit Task")
                .font(.lifeTrack(.title, weight: .bold))
                .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

            InfoTipButton(
                message: existingTask == nil
                    ? "Capture the next step with enough context to act on it."
                    : "Refine the details and keep reminders accurate."
            )

            Spacer(minLength: 0)
        }
    }

    private var taskCard: some View {
        SectionCardView {
            SectionHeaderView(
                title: "Task Details",
                infoMessage: "Name it clearly and classify it."
            )

            VStack(alignment: .leading, spacing: 7) {
                Text("Title")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                ZStack(alignment: .leading) {
                    if title.isEmpty {
                        Text("e.g. Send quarterly insurance update")
                            .font(.title3.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.placeholderText)
                            .padding(.horizontal, 14)
                            .allowsHitTesting(false)
                    }

                    TextField("", text: $title)
                        .font(.title3.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                        .textInputAutocapitalization(.sentences)
                        .padding(13)
                }
                .background(LifeTrackTheme.ColorPalette.backgroundTop, in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
                .overlay {
                    RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                        .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.9), lineWidth: 0.8)
                }
            }

            VStack(alignment: .leading, spacing: 8) {
                Text("Category")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                LazyVGrid(
                    columns: [GridItem(.adaptive(minimum: 92), spacing: 8, alignment: .leading)],
                    alignment: .leading,
                    spacing: 8
                ) {
                    ForEach(categoryOptions) { option in
                        Button {
                            categoryRawValue = option.id
                            pendingCategoryOption = nil
                        } label: {
                            CategoryChipView(option: option, isSelected: categoryRawValue == option.id)
                        }
                        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                    }
                }

                Button {
                    isShowingCategoryManager = true
                } label: {
                    HStack(spacing: 8) {
                        Image(systemName: "plus")
                        Text("Custom category")
                    }
                    .font(.footnote.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Capsule())
                }
                .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.96))
            }
        }
    }

    private var voiceCard: some View {
        VoiceInputCard(
            transcript: $voiceTranscript,
            isRecording: voiceInput.isRecording,
            audioLevel: voiceInput.audioLevel,
            feedbackMessage: voiceInput.feedbackMessage,
            authorizationMessage: voiceInput.authorizationMessage,
            isEnhancing: isAIEnhancing,
            onToggleRecording: { voiceInput.toggleRecording() },
            onApplyTranscript: { applyVoiceTranscript(voiceTranscript, force: true) },
            onClearTranscript: {
                voiceInput.clearTranscript()
                voiceTranscript = ""
                isAIEnhancing = false
            }
        )
    }

    private var planningCard: some View {
        SectionCardView {
            SectionHeaderView(
                title: "Planning",
                infoMessage: "Help LifeTrack choose what matters today."
            )

            VStack(alignment: .leading, spacing: 8) {
                Text("Priority")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                HStack(spacing: 8) {
                    ForEach(TaskPriority.allCases) { option in
                        Button {
                            priority = option
                        } label: {
                            PriorityPillView(priority: option, isSelected: priority == option)
                        }
                        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                    }
                }
            }

            VStack(alignment: .leading, spacing: 8) {
                Text("Repeat")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                LazyVGrid(
                    columns: [GridItem(.adaptive(minimum: 92), spacing: 8, alignment: .leading)],
                    alignment: .leading,
                    spacing: 8
                ) {
                    ForEach(TaskRecurrence.allCases) { option in
                        Button {
                            recurrence = option
                        } label: {
                            RecurrencePillView(recurrence: option, isSelected: recurrence == option)
                        }
                        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                    }
                }
            }
        }
    }

    private var dateCard: some View {
        SectionCardView {
            SectionHeaderView(
                title: "Due Date",
                infoMessage: "LifeTrack will schedule a reminder."
            )

            VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.medium) {
                HStack(spacing: LifeTrackTheme.Spacing.medium) {
                    Image(systemName: "calendar.badge.clock")
                        .font(.system(size: 17, weight: .semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                        .frame(width: LifeTrackTheme.IconSize.largeCircle, height: LifeTrackTheme.IconSize.largeCircle)
                        .background(LifeTrackTheme.ColorPalette.accentSoft, in: Circle())

                    VStack(alignment: .leading, spacing: 3) {
                        Text(dueDate.weekdayDateString)
                            .font(.subheadline.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                            .lineLimit(1)
                            .minimumScaleFactor(0.85)

                        Text(dueDate.timeString)
                            .font(.footnote)
                            .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                            .lineLimit(1)
                    }

                    Spacer(minLength: 0)
                }

                VStack(spacing: 0) {
                    DateSelectionRow(
                        title: "Date",
                        value: dueDate.formatted(Date.FormatStyle().month(.abbreviated).day().year()),
                        symbolName: "calendar",
                        action: { activeDueDatePicker = .date }
                    )

                    Divider()
                        .padding(.leading, 54)

                    DateSelectionRow(
                        title: "Time",
                        value: dueDate.timeString,
                        symbolName: "clock",
                        action: { activeDueDatePicker = .time }
                    )
                }
                .padding(.horizontal, 11)
                .padding(.vertical, 4)
                .background(LifeTrackTheme.ColorPalette.cardElevated.opacity(0.75), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))

                durationSelector
            }
            .padding(11)
            .background(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.85), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous)
                    .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.85), lineWidth: 0.8)
            }
        }
    }

    private var locationCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Location Reminder", subtitle: "Trigger when you arrive or leave a place.")

            if let config = locationConfig {
                HStack(spacing: 12) {
                    Image(systemName: config.onArrival ? "arrow.down.circle.fill" : "arrow.up.circle.fill")
                        .font(.system(size: 20, weight: .semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.accent)

                    VStack(alignment: .leading, spacing: 2) {
                        Text(config.name.isEmpty ? "Selected Place" : config.name)
                            .font(.subheadline.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                            .lineLimit(1)
                        Text("\(config.onArrival ? "On arrival" : "On departure") · \(Int(config.radius))m radius")
                            .font(.caption)
                            .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                    }

                    Spacer()

                    Button {
                        locationConfig = nil
                    } label: {
                        Image(systemName: "xmark.circle.fill")
                            .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                    }
                }

                Button {
                    isShowingLocationPicker = true
                } label: {
                    Text("Change Location")
                        .font(.caption.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                }
            } else {
                Button {
                    isShowingLocationPicker = true
                } label: {
                    HStack(spacing: 10) {
                        Image(systemName: "location.circle.fill")
                            .font(.system(size: 20))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                        Text("Add Location Trigger")
                            .font(.subheadline.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                        Spacer()
                        Image(systemName: "chevron.right")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                    }
                }
                .buttonStyle(.plain)
            }
        }
    }

    private var financialDetailsCard: some View {
        TaskFinancialDetailsSection(
            isEnabled: $financialEnabled,
            financialType: $financialType,
            plannedAmountText: $plannedAmountText,
            actualAmountText: $actualAmountText,
            currencyCode: $currencyCode,
            budgetCategory: $budgetCategory,
            hasPaymentDate: $hasPaymentDate,
            paymentDate: $paymentDate,
            linkOption: $financialLinkOption,
            notes: $financialNotes,
            includeInMonthlySpending: $includeInMonthlySpending,
            markPlannedOnCreate: $markPlannedOnCreate,
            existingTaskHasActivity: existingTask?.hasFinancialActivity ?? false
        )
    }

    private var durationSelector: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: LifeTrackTheme.Spacing.small) {
                Image(systemName: "timer")
                    .font(.system(size: 13, weight: .bold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)

                Text("Duration")
                    .font(.footnote.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                Spacer(minLength: 0)

                Text(durationTitle(for: durationMinutes))
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
            }

            LazyVGrid(
                columns: [GridItem(.adaptive(minimum: 70), spacing: 8, alignment: .leading)],
                alignment: .leading,
                spacing: 8
            ) {
                ForEach(durationOptions, id: \.self) { option in
                    Button {
                        durationMinutes = option
                    } label: {
                        Text(durationTitle(for: option))
                            .font(.caption.weight(.bold))
                            .foregroundStyle(durationMinutes == option ? .white : LifeTrackTheme.ColorPalette.secondaryText)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 8)
                            .background(durationChipBackground(isSelected: durationMinutes == option), in: Capsule())
                            .overlay {
                                Capsule()
                                    .stroke(durationMinutes == option ? Color.white.opacity(0.22) : LifeTrackTheme.ColorPalette.hairline.opacity(0.82), lineWidth: 0.8)
                            }
                    }
                    .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                }
            }
        }
        .padding(11)
        .background(LifeTrackTheme.ColorPalette.cardElevated.opacity(0.66), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
    }

    private var notesCard: some View {
        SectionCardView {
            SectionHeaderView(
                title: "Notes",
                infoMessage: "Add context, links, or draft text."
            )

            ZStack(alignment: .topLeading) {
                TextEditor(text: $notes)
                    .font(.body)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                    .frame(minHeight: 126)
                    .scrollContentBackground(.hidden)
                    .padding(9)

                if notes.isEmpty {
                    Text("Write the details that will make this task easier later...")
                        .font(.body)
                        .foregroundStyle(LifeTrackTheme.ColorPalette.placeholderText)
                        .padding(.horizontal, 16)
                        .padding(.vertical, 18)
                        .allowsHitTesting(false)
                }
            }
            .background(LifeTrackTheme.ColorPalette.backgroundTop, in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                    .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.9), lineWidth: 0.8)
            }
        }
    }

    private var advancedFieldsCard: some View {
        let fields = selectedCategory.advancedFields
        return Group {
            if !fields.isEmpty {
                SectionCardView {
                    HStack(alignment: .center, spacing: LifeTrackTheme.Spacing.medium) {
                        Button(action: toggleAdvancedExpansion) {
                            Text("Advanced")
                                .font(.headline.weight(.semibold))
                                .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                        }
                        .buttonStyle(.plain)

                        InfoTipButton(message: "Extra \(selectedCategory.title.lowercased()) fields — optional.")

                        Spacer(minLength: 0)

                        Button(action: toggleAdvancedExpansion) {
                            HStack(spacing: 10) {
                                if !advancedFilledKeys.isEmpty {
                                    Text("\(advancedFilledKeys.count)")
                                        .font(.caption.weight(.bold))
                                        .foregroundStyle(.white)
                                        .padding(.horizontal, 8)
                                        .padding(.vertical, 3)
                                        .background(LifeTrackTheme.ColorPalette.accent, in: Capsule())
                                }

                                Image(systemName: isAdvancedExpanded ? "chevron.up" : "chevron.down")
                                    .font(.system(size: 13, weight: .bold))
                                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                            }
                        }
                        .buttonStyle(.plain)
                    }

                    if isAdvancedExpanded {
                        VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.medium) {
                            ForEach(fields) { field in
                                advancedFieldRow(for: field)
                            }
                        }
                        .padding(.top, LifeTrackTheme.Spacing.small)
                    }
                }
            }
        }
    }

    private var advancedFilledKeys: [String] {
        selectedCategory.advancedFields
            .map(\.rawValue)
            .filter { key in
                !(advancedFieldValues[key]?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true)
            }
    }

    private func toggleAdvancedExpansion() {
        withAnimation(.easeInOut(duration: 0.22)) {
            isAdvancedExpanded.toggle()
        }
    }

    private func handleFloatingVoiceButtonTap(scrollProxy: ScrollViewProxy) {
        if voiceInput.isRecording {
            voiceInput.toggleRecording()
            return
        }

        withAnimation(.easeOut(duration: 0.28)) {
            scrollProxy.scrollTo(NewTaskViewAnchor.voiceCard, anchor: .top)
        }

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.12) {
            if !voiceInput.isRecording {
                voiceInput.toggleRecording()
            }
        }
    }

    @ViewBuilder
    private func advancedFieldRow(for field: AdvancedTaskField) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 6) {
                Image(systemName: field.symbolName)
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                Text(field.title)
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
            }

            TextField(
                field.placeholder,
                text: Binding(
                    get: { advancedFieldValues[field.rawValue] ?? "" },
                    set: { advancedFieldValues[field.rawValue] = $0 }
                )
            )
            .font(.body)
            .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
            .padding(.horizontal, 14)
            .padding(.vertical, 11)
            .background(
                LifeTrackTheme.ColorPalette.backgroundTop,
                in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
            )
            .overlay {
                RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                    .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.9), lineWidth: 0.8)
            }
        }
    }

    private var documentCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Document", subtitle: "Scan a document or attach a file stored locally with this task.")

            HStack(spacing: LifeTrackTheme.Spacing.small) {
                DocumentCaptureButton(
                    title: "Scan",
                    subtitle: "Use camera",
                    symbolName: "doc.viewfinder",
                    tint: LifeTrackTheme.ColorPalette.accent,
                    isAvailable: DocumentScanAvailability.isSupported
                ) {
                    isScanningDocument = true
                }

                DocumentCaptureButton(
                    title: "Attach",
                    subtitle: "From files",
                    symbolName: "paperclip",
                    tint: LifeTrackTheme.ColorPalette.success,
                    isAvailable: true
                ) {
                    isImportingDocument = true
                }
            }

            AttachmentButton(
                documentDisplayName: documentDisplayName,
                onAttach: { isImportingDocument = true },
                onRemove: documentDisplayName == nil ? nil : { removeDocument() }
            )

            if let documentError {
                Text(documentError)
                    .font(.footnote.weight(.medium))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.danger)
            }

            if isAnalyzingDocument {
                HStack(spacing: LifeTrackTheme.Spacing.small) {
                    ProgressView()
                        .tint(LifeTrackTheme.ColorPalette.accent)

                    Text("Reading document locally...")
                        .font(.footnote.weight(.medium))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }
                .padding(11)
                .background(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.86), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
            } else if hasDocumentAnalysis {
                DocumentIntelligenceView(
                    summary: documentAnalysisSummary,
                    suggestedTitle: documentSuggestedTitle,
                    suggestedDueDate: documentSuggestedDueDate,
                    keywords: documentKeywords,
                    extractedText: documentExtractedText,
                    hasApplied: didApplyDocumentSuggestion,
                    onApplySuggestion: applyDocumentSuggestion
                )
            }
        }
    }

    private var templateActionCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Template Action", subtitle: "This shortcut stays attached to the task.")

            HStack(spacing: LifeTrackTheme.Spacing.medium) {
                Image(systemName: "envelope.badge")
                    .font(.system(size: 17, weight: .semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .frame(width: LifeTrackTheme.IconSize.largeCircle, height: LifeTrackTheme.IconSize.largeCircle)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Circle())

                VStack(alignment: .leading, spacing: 4) {
                    Text("Email draft")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                    Text("Open a pre-filled email from the task detail screen.")
                        .font(.footnote)
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }
            }
        }
    }

    private var statusCard: some View {
        SectionCardView {
            Toggle(isOn: $isCompleted) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Completed")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                    Text("Completed tasks will not schedule reminders.")
                        .font(.footnote)
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }
            }
            .tint(LifeTrackTheme.ColorPalette.success)
        }
    }

    private var canSave: Bool {
        !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private var categoryOptions: [TaskCategoryOption] {
        TaskCategoryOption.all(customCategories: customCategories)
    }

    private var selectedCategoryOption: TaskCategoryOption {
        if let pendingCategoryOption, pendingCategoryOption.id == categoryRawValue {
            return pendingCategoryOption
        }

        return TaskCategoryOption.resolved(rawValue: categoryRawValue, customCategories: customCategories)
    }

    private func removeDocument() {
        if documentStorageName != originalDocumentStorageName {
            DocumentStore.delete(storageName: documentStorageName)
        }
        documentStorageName = nil
        documentDisplayName = nil
        clearDocumentAnalysis()

        if notes == lastAutoGeneratedDocumentNotes {
            notes = ""
        }
        lastAutoGeneratedDocumentNotes = ""
    }

    private func handleScanResult(_ result: Result<URL, Error>) {
        switch result {
        case .success(let url):
            defer { try? FileManager.default.removeItem(at: url) }

            do {
                let pendingDocumentStorageName = documentStorageName
                let storedDocument = try DocumentStore.saveSecurityScopedFile(from: url)
                if pendingDocumentStorageName != originalDocumentStorageName {
                    DocumentStore.delete(storageName: pendingDocumentStorageName)
                }
                documentStorageName = storedDocument.storageName
                documentDisplayName = storedDocument.displayName
                documentError = nil
                analyzeDocument(storageName: storedDocument.storageName, displayName: storedDocument.displayName)
                LifeTrackHaptics.lightImpact()
            } catch {
                documentError = "Scan could not be saved."
                isAnalyzingDocument = false
            }
        case .failure(let error):
            if case DocumentScannerView.ScanError.cancelled = error {
                return
            }
            documentError = "Scan could not be completed."
            isAnalyzingDocument = false
        }
    }

    private func handleDocumentImport(_ result: Result<[URL], Error>) {
        switch result {
        case .success(let urls):
            guard let url = urls.first else {
                return
            }

            do {
                let pendingDocumentStorageName = documentStorageName
                let storedDocument = try DocumentStore.saveSecurityScopedFile(from: url)
                if pendingDocumentStorageName != originalDocumentStorageName {
                    DocumentStore.delete(storageName: pendingDocumentStorageName)
                }
                documentStorageName = storedDocument.storageName
                documentDisplayName = storedDocument.displayName
                documentError = nil
                analyzeDocument(storageName: storedDocument.storageName, displayName: storedDocument.displayName)
            } catch {
                documentError = "Document could not be attached."
                isAnalyzingDocument = false
            }
        case .failure:
            documentError = "Document could not be attached."
            isAnalyzingDocument = false
        }
    }

    private func analyzeDocument(storageName: String, displayName: String) {
        guard let url = DocumentStore.url(for: storageName) else {
            clearDocumentAnalysis()
            documentError = "Document was attached, but could not be read yet."
            return
        }

        clearDocumentAnalysis()
        isAnalyzingDocument = true

        Task {
            let result = await DocumentAnalysisManager.analyze(url: url, displayName: displayName)
            await MainActor.run {
                guard documentStorageName == storageName else {
                    return
                }

                documentExtractedText = result.extractedText
                documentAnalysisSummary = result.summary
                documentSuggestedTitle = result.suggestedTitle
                documentSuggestedDueDate = result.suggestedDueDate
                documentKeywords = result.keywords
                isAnalyzingDocument = false

                applyAutoGeneratedDocumentNotes(displayName: displayName, result: result)
            }
        }
    }

    private func applyAutoGeneratedDocumentNotes(displayName: String, result: DocumentAnalysisResult) {
        let autoNotes = buildAutoDocumentNotes(displayName: displayName, result: result)
        guard !autoNotes.isEmpty else { return }

        let trimmed = notes.trimmingCharacters(in: .whitespacesAndNewlines)

        if trimmed.isEmpty || notes == lastAutoGeneratedDocumentNotes {
            notes = autoNotes
            lastAutoGeneratedDocumentNotes = autoNotes
        }
    }

    private func buildAutoDocumentNotes(displayName: String, result: DocumentAnalysisResult) -> String {
        var lines: [String] = ["Attached: \(displayName)"]

        if !result.keywords.isEmpty {
            lines.append("Detected: \(result.keywords.prefix(5).joined(separator: ", "))")
        }

        if let suggestedDueDate = result.suggestedDueDate {
            lines.append("Date found: \(suggestedDueDate.weekdayDateString)")
        }

        let excerpt = documentExcerpt(from: result.extractedText)
        if !excerpt.isEmpty {
            lines.append("")
            lines.append(excerpt)
        }

        return lines.joined(separator: "\n")
    }

    private func documentExcerpt(from text: String) -> String {
        let normalized = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else { return "" }

        let maxLength = 240
        if normalized.count <= maxLength {
            return normalized
        }

        let clipped = normalized.prefix(maxLength)
        if let lastSpace = clipped.lastIndex(of: " ") {
            return clipped[..<lastSpace] + "…"
        }

        return clipped + "…"
    }

    private func clearDocumentAnalysis() {
        documentExtractedText = ""
        documentAnalysisSummary = nil
        documentSuggestedTitle = nil
        documentSuggestedDueDate = nil
        documentKeywords = []
        didApplyDocumentSuggestion = false
    }

    private var hasDocumentAnalysis: Bool {
        documentAnalysisSummary != nil ||
            documentSuggestedTitle != nil ||
            documentSuggestedDueDate != nil ||
            !documentKeywords.isEmpty ||
            !documentExtractedText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func applyDocumentSuggestion() {
        var didChange = false

        if let suggestedTitle = documentSuggestedTitle, !suggestedTitle.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            withAnimation(.easeOut(duration: 0.2)) {
                title = suggestedTitle
            }
            didChange = true
        }

        if let documentSuggestedDueDate {
            withAnimation(.easeOut(duration: 0.2)) {
                dueDate = documentSuggestedDueDate
            }
            didChange = true
        }

        if documentKeywords.contains("insurance") || documentKeywords.contains("invoice") || documentKeywords.contains("bill") || documentKeywords.contains("tax") {
            categoryRawValue = TaskCategory.finance.rawValue
            pendingCategoryOption = nil
            didChange = true
        } else if documentKeywords.contains("appointment") || documentKeywords.contains("medical") {
            categoryRawValue = TaskCategory.health.rawValue
            pendingCategoryOption = nil
            didChange = true
        } else if documentKeywords.contains("school") || documentKeywords.contains("application") {
            categoryRawValue = TaskCategory.personal.rawValue
            pendingCategoryOption = nil
            didChange = true
        }

        if didChange {
            LifeTrackHaptics.lightImpact()
            withAnimation(.easeOut(duration: 0.22)) {
                didApplyDocumentSuggestion = true
            }
            documentScrollRequest = UUID()
        }
    }

    private func applyVoiceTranscript(_ transcript: String, force: Bool = false) {
        let cleanedTranscript = transcript.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleanedTranscript.isEmpty else {
            return
        }

        let draft = VoiceTaskParser.parse(cleanedTranscript)

        if let draftTitle = draft.title, force || title.isEmpty || title == lastVoiceGeneratedTitle {
            title = draftTitle
            lastVoiceGeneratedTitle = draftTitle
        }

        if let draftCategory = draft.category, force || !didApplyVoiceCategory {
            categoryRawValue = draftCategory.rawValue
            pendingCategoryOption = nil
            didApplyVoiceCategory = true
        }

        if let draftDueDate = draft.dueDate, force || !didApplyVoiceDueDate {
            dueDate = draftDueDate
            didApplyVoiceDueDate = true
        }

        let trimmedNotes = notes.trimmingCharacters(in: .whitespacesAndNewlines)
        let notesIsOverridableByVoice =
            trimmedNotes.isEmpty ||
            notes == lastVoiceGeneratedNotes ||
            (trimmedNotes == lastAutoGeneratedDocumentNotes.trimmingCharacters(in: .whitespacesAndNewlines) && !lastAutoGeneratedDocumentNotes.isEmpty)

        if let draftNotes = draft.notes, !draftNotes.isEmpty, force || notesIsOverridableByVoice {
            notes = draftNotes
            lastVoiceGeneratedNotes = draftNotes
        } else if draft.notes == nil, notes == lastVoiceGeneratedNotes, !lastVoiceGeneratedNotes.isEmpty {
            notes = ""
            lastVoiceGeneratedNotes = ""
        }

        if let draftPriority = draft.priority, force {
            priority = draftPriority
        }

        applyFinancialDraft(draft, force: force)
    }

    private func applyFinancialDraft(_ draft: VoiceTaskDraft, force: Bool) {
        let hasFinancialValues =
            draft.financialEnabled == true ||
            draft.financialType != nil ||
            draft.plannedAmount != nil ||
            draft.actualAmount != nil ||
            draft.currencyCode != nil ||
            draft.budgetCategory != nil ||
            draft.paymentDate != nil ||
            draft.linkedBudgetId != nil ||
            draft.linkedGoalId != nil ||
            draft.includeInMonthlySpending != nil ||
            draft.markPlannedOnCreate != nil ||
            draft.financialNotes != nil

        guard hasFinancialValues else { return }

        let wasFinancialEnabled = financialEnabled
        if force || !financialEnabled || draft.financialEnabled == true {
            financialEnabled = true
        }

        if let draftType = draft.financialType, force || !wasFinancialEnabled {
            financialType = draftType
        }

        if let plannedAmount = draft.plannedAmount,
           force || plannedAmountText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            plannedAmountText = Self.amountInputString(plannedAmount)
        }

        if let actualAmount = draft.actualAmount,
           force || actualAmountText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            actualAmountText = Self.amountInputString(actualAmount)
        }

        if draft.currencyCode != nil,
           force || currencyCode == MoneyCurrency.defaultCode {
            currencyCode = Self.currentMoneyCurrencyCode
        }

        if let draftBudgetCategory = draft.budgetCategory,
           force || budgetCategory.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            budgetCategory = draftBudgetCategory
        }

        if let draftPaymentDate = draft.paymentDate, force || !hasPaymentDate {
            paymentDate = draftPaymentDate
            hasPaymentDate = true
        }

        if (draft.linkedBudgetId != nil || draft.linkedGoalId != nil), force || !wasFinancialEnabled {
            financialLinkOption = MoneyLinkOption.resolved(
                budgetId: draft.linkedBudgetId,
                goalId: draft.linkedGoalId
            )
        }

        if let include = draft.includeInMonthlySpending, force || !wasFinancialEnabled {
            includeInMonthlySpending = include
        }

        if let markPlanned = draft.markPlannedOnCreate, force || !wasFinancialEnabled {
            markPlannedOnCreate = markPlanned
        }

        if let draftNotes = draft.financialNotes,
           force || financialNotes.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            financialNotes = draftNotes
        }
    }

    private func enhanceVoiceDraftWithAI() async {
        if !voiceTranscriptDisclosureShown {
            await MainActor.run { isShowingVoiceTranscriptDisclosure = true }
            return
        }

        isAIEnhancing = true
        defer { isAIEnhancing = false }

        guard let enhanced = await voiceEnhancer.enhance(transcript: voiceTranscript) else { return }

        withAnimation(.easeOut(duration: 0.22)) {
            applyVoiceTranscript(voiceTranscript, force: false)

            if let t = enhanced.title, !t.isEmpty {
                title = t
                lastVoiceGeneratedTitle = t
            }

            if let n = enhanced.notes, !n.isEmpty {
                notes = n
                lastVoiceGeneratedNotes = n
            }

            if let d = enhanced.dueDate {
                dueDate = d
                didApplyVoiceDueDate = true
            }

            if let cat = enhanced.category {
                categoryRawValue = cat.rawValue
                didApplyVoiceCategory = true
            }

            if let pri = enhanced.priority {
                priority = pri
            }

            if !enhanced.advancedFields.isEmpty {
                let allowedKeys = Set(selectedCategory.advancedFields.map(\.rawValue))
                for (key, value) in enhanced.advancedFields where allowedKeys.contains(key) {
                    let existing = advancedFieldValues[key]?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
                    if existing.isEmpty {
                        advancedFieldValues[key] = value
                    }
                }
                if !advancedFieldValues.isEmpty {
                    isAdvancedExpanded = true
                }
            }

            applyFinancialDraft(enhanced, force: false)
        }
    }

    private func save() {
        let cleanedTitle = title.trimmingCharacters(in: .whitespacesAndNewlines)
        let now = Date()
        let wasCompleted = existingTask?.isCompleted ?? false

        let task: LifeTask
        if let existingTask {
            task = existingTask
            if originalDocumentStorageName != documentStorageName {
                DocumentStore.delete(storageName: originalDocumentStorageName)
            }
            task.title = cleanedTitle
            task.categoryRawValue = categoryRawValue
            task.dueDate = dueDate
            task.isCompleted = isCompleted
            task.notes = notes
            task.templateAction = templateAction
            task.priority = priority
            task.recurrence = recurrence
            task.scheduledDurationMinutes = durationMinutes
            task.documentStorageName = documentStorageName
            task.documentDisplayName = documentDisplayName
            task.documentExtractedText = documentExtractedText
            task.documentAnalysisSummary = documentAnalysisSummary
            task.documentSuggestedTitle = documentSuggestedTitle
            task.documentSuggestedDueDate = documentSuggestedDueDate
            task.documentKeywords = documentKeywords
            task.locationReminderName = locationConfig?.name
            task.locationReminderLatitude = locationConfig?.latitude
            task.locationReminderLongitude = locationConfig?.longitude
            task.locationReminderRadius = locationConfig?.radius
            task.locationReminderOnArrival = locationConfig?.onArrival ?? true
            task.advancedFields = sanitizedAdvancedFields()
            applyFinancialDetails(to: task)
            task.updatedAt = now
        } else {
            task = LifeTask(
                title: cleanedTitle,
                category: selectedCategory,
                categoryRawValue: categoryRawValue,
                dueDate: dueDate,
                isCompleted: isCompleted,
                notes: notes,
                templateAction: templateAction,
                priority: priority,
                recurrence: recurrence,
                estimatedDurationMinutes: durationMinutes,
                documentStorageName: documentStorageName,
                documentDisplayName: documentDisplayName,
                documentExtractedText: documentExtractedText,
                documentAnalysisSummary: documentAnalysisSummary,
                documentSuggestedTitle: documentSuggestedTitle,
                documentSuggestedDueDate: documentSuggestedDueDate,
                documentKeywords: documentKeywords,
                createdAt: now,
                updatedAt: now
            )
            task.locationReminderName = locationConfig?.name
            task.locationReminderLatitude = locationConfig?.latitude
            task.locationReminderLongitude = locationConfig?.longitude
            task.locationReminderRadius = locationConfig?.radius
            task.locationReminderOnArrival = locationConfig?.onArrival ?? true
            task.advancedFields = sanitizedAdvancedFields()
            applyFinancialDetails(to: task)
            if task.isHabit { task.habitGroupID = task.id }
            modelContext.insert(task)
        }

        let nextRecurringTask: LifeTask?
        if !wasCompleted && task.isCompleted {
            nextRecurringTask = task.nextRecurringTask(completedAt: now)
            if let nextRecurringTask {
                modelContext.insert(nextRecurringTask)
            }
        } else {
            nextRecurringTask = nil
        }

        try? modelContext.save()
        ReminderScheduler.synchronizeReminder(
            taskID: task.id,
            title: task.title,
            categoryTitle: selectedCategoryOption.title,
            dueDate: task.dueDate,
            isCompleted: task.isCompleted,
            isHighPriority: task.priority == .high,
            detailLine: task.reminderDetailLine(categoryTitle: selectedCategoryOption.title)
        )
        if let nextRecurringTask {
            TaskLifecycleManager.synchronizeReminder(
                for: nextRecurringTask,
                customCategories: customCategories
            )
        }
        LocationReminderManager.shared.cancelRegion(for: task.id)
        if task.hasLocationReminder && !task.isCompleted {
            LocationReminderManager.shared.scheduleRegion(for: task)
        }
        didSave = true
        if isFreshNewTask {
            NewTaskDraftStore.clear()
        }
        dismiss()
    }

    private func applyFinancialDetails(to task: LifeTask) {
        task.financialEnabled = financialEnabled
        task.financialType = financialType
        task.plannedAmount = financialEnabled ? parseAmount(plannedAmountText) : 0
        let actual = parseAmount(actualAmountText)
        task.actualAmount = financialEnabled && actual > 0 ? actual : nil
        task.currencyCode = MoneyCurrency.normalized(currencyCode)
        task.budgetCategory = financialEnabled ? budgetCategory.trimmingCharacters(in: .whitespacesAndNewlines) : ""
        task.paymentDate = financialEnabled && hasPaymentDate ? paymentDate : nil
        task.linkedBudgetId = financialEnabled ? financialLinkOption.budgetId : nil
        task.linkedGoalId = financialEnabled ? financialLinkOption.goalId : nil
        task.includeInMonthlySpending = includeInMonthlySpending
        task.markPlannedOnCreate = markPlannedOnCreate
        task.financialNotes = financialEnabled ? financialNotes : ""
    }

    private func parseAmount(_ value: String) -> Double {
        let normalized = value
            .replacingOccurrences(of: ",", with: ".")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return Double(normalized) ?? 0
    }

    private static func amountInputString(_ amount: Double?) -> String {
        guard let amount, amount > 0 else { return "" }
        if amount.rounded(.down) == amount {
            return String(Int(amount))
        }
        return String(format: "%.2f", amount)
    }

    private var selectedCategory: TaskCategory {
        TaskCategory(rawValue: categoryRawValue) ?? .other
    }

    private func durationTitle(for minutes: Int) -> String {
        if minutes < 60 {
            return "\(minutes)m"
        }

        let hours = minutes / 60
        let remainingMinutes = minutes % 60
        if remainingMinutes == 0 {
            return "\(hours)h"
        }

        return "\(hours)h \(remainingMinutes)m"
    }

    private func durationChipBackground(isSelected: Bool) -> some ShapeStyle {
        if isSelected {
            return AnyShapeStyle(LifeTrackTheme.ColorPalette.accentGradient)
        }

        return AnyShapeStyle(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.86))
    }
}

private enum NewTaskViewAnchor: Hashable {
    case voiceCard
    case taskCard
}

#Preview("New Task") {
    let configuration = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(for: LifeTask.self, CustomTaskCategory.self, configurations: configuration)

    return NewTaskView(template: TaskTemplate.common.first)
        .modelContainer(container)
}
