//
//  NewTaskView.swift
//  LifeTrack
//
//  Created by Halalisani Mbanjwa on 2026/04/18.
//

import SwiftData
import SwiftUI
import UniformTypeIdentifiers
import VisionKit

struct NewTaskView: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext
    @Query(sort: \CustomTaskCategory.title) private var customCategories: [CustomTaskCategory]

    @StateObject private var voiceInput = VoiceTaskInputManager()

    private let existingTask: LifeTask?
    private let originalDocumentStorageName: String?
    private let autoStartVoice: Bool
    @State private var didAutoStartVoice = false

    @State private var title: String
    @State private var categoryRawValue: String
    @State private var dueDate: Date
    @State private var isCompleted: Bool
    @State private var notes: String
    @State private var templateAction: TaskTemplateAction
    @State private var priority: TaskPriority
    @State private var recurrence: TaskRecurrence
    @State private var durationMinutes: Int
    @State private var documentStorageName: String?
    @State private var documentDisplayName: String?
    @State private var documentExtractedText: String
    @State private var documentAnalysisSummary: String?
    @State private var documentSuggestedTitle: String?
    @State private var documentSuggestedDueDate: Date?
    @State private var documentKeywords: [String]
    @State private var isImportingDocument = false
    @State private var isScanningDocument = false
    @State private var isAnalyzingDocument = false
    @State private var isShowingCategoryManager = false
    @State private var isShowingTaskDataExchange = false
    @State private var activeDueDatePicker: DueDatePickerMode?
    @State private var taskDataMode: TaskDataExchangeEntryMode = .importTasks
    @State private var pendingCategoryOption: TaskCategoryOption?
    @State private var documentError: String?
    @State private var didSave = false
    @State private var voiceTranscript = ""
    @State private var lastVoiceGeneratedTitle = ""
    @State private var lastVoiceGeneratedNotes = ""
    @State private var didApplyVoiceCategory = false
    @State private var didApplyVoiceDueDate = false
    @State private var didApplyDocumentSuggestion = false
    @State private var documentScrollRequest: UUID?
    @State private var lastAutoGeneratedDocumentNotes = ""
    @State private var locationConfig: LocationReminderConfig?
    @State private var isShowingLocationPicker = false
    @AppStorage(LifeTrackSettings.Keys.isProEnabled) private var isProEnabled = false

    private let durationOptions = [15, 30, 45, 60, 90, 120]

    init(task: LifeTask? = nil, template: TaskTemplate? = nil, autoStartVoice: Bool = false) {
        existingTask = task
        originalDocumentStorageName = task?.documentStorageName
        self.autoStartVoice = autoStartVoice

        let template = template
        _title = State(initialValue: task?.title ?? template?.title ?? "")
        _categoryRawValue = State(initialValue: task?.categoryRawValue ?? template?.category.rawValue ?? TaskCategory.personal.rawValue)
        _dueDate = State(initialValue: task?.dueDate ?? template?.dueDate ?? Date())
        _isCompleted = State(initialValue: task?.isCompleted ?? false)
        _notes = State(initialValue: task?.notes ?? template?.notes ?? "")
        _templateAction = State(initialValue: task?.templateAction ?? template?.action ?? .none)
        _priority = State(initialValue: task?.priority ?? template?.priority ?? .normal)
        _recurrence = State(initialValue: task?.recurrence ?? template?.recurrence ?? .none)
        _durationMinutes = State(initialValue: task?.scheduledDurationMinutes ?? template?.estimatedDurationMinutes ?? 30)
        _documentStorageName = State(initialValue: task?.documentStorageName)
        _documentDisplayName = State(initialValue: task?.documentDisplayName)
        _documentExtractedText = State(initialValue: task?.documentExtractedText ?? "")
        _documentAnalysisSummary = State(initialValue: task?.documentAnalysisSummary)
        _documentSuggestedTitle = State(initialValue: task?.documentSuggestedTitle)
        _documentSuggestedDueDate = State(initialValue: task?.documentSuggestedDueDate)
        _documentKeywords = State(initialValue: task?.documentKeywords ?? [])
        if let lat = task?.locationReminderLatitude, let lon = task?.locationReminderLongitude {
            _locationConfig = State(initialValue: LocationReminderConfig(
                name: task?.locationReminderName ?? "",
                latitude: lat,
                longitude: lon,
                radius: task?.locationReminderRadius ?? 150,
                onArrival: task?.locationReminderOnArrival ?? true
            ))
        }
    }

    var body: some View {
        NavigationStack {
            ZStack {
                LifeTrackTheme.appBackground
                    .ignoresSafeArea()

                ScrollViewReader { scrollProxy in
                    ScrollView {
                        VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.large) {
                            header

                            taskDataShortcutCard

                            voiceCard

                            taskCard
                                .id(NewTaskViewAnchor.taskCard)

                            planningCard

                            dateCard

                            if isProEnabled {
                                locationCard
                            }

                            notesCard

                            documentCard

                        if templateAction == .email {
                            templateActionCard
                        }

                        if existingTask != nil {
                            statusCard
                        }
                    }
                        .padding(.horizontal, LifeTrackTheme.Spacing.xLarge)
                        .padding(.top, LifeTrackTheme.Spacing.medium)
                        .padding(.bottom, 30)
                    }
                    .scrollIndicators(.hidden)
                    .onChange(of: documentScrollRequest) { _, newValue in
                        guard newValue != nil else { return }
                        withAnimation(.easeOut(duration: 0.28)) {
                            scrollProxy.scrollTo(NewTaskViewAnchor.taskCard, anchor: .top)
                        }
                        documentScrollRequest = nil
                    }
                }
            }
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button("Save", action: save)
                        .fontWeight(.semibold)
                        .disabled(!canSave)
                }
            }
            .fileImporter(
                isPresented: $isImportingDocument,
                allowedContentTypes: [.item],
                allowsMultipleSelection: false,
                onCompletion: handleDocumentImport
            )
            .fullScreenCover(isPresented: $isScanningDocument) {
                DocumentScannerView { result in
                    isScanningDocument = false
                    handleScanResult(result)
                }
                .ignoresSafeArea()
            }
            .sheet(isPresented: $isShowingLocationPicker) {
                LocationPickerView { config in
                    locationConfig = config
                }
                .presentationDetents([.large])
                .presentationDragIndicator(.visible)
            }
            .sheet(isPresented: $isShowingCategoryManager) {
                CategoryManagerView { option in
                    categoryRawValue = option.id
                    pendingCategoryOption = option
                }
                .presentationDetents([.large])
                .presentationDragIndicator(.visible)
            }
            .sheet(isPresented: $isShowingTaskDataExchange) {
                NavigationStack {
                    TaskDataExchangeView(initialMode: taskDataMode, showsCloseButton: true)
                }
                .presentationDetents([.large])
                .presentationDragIndicator(.visible)
            }
            .sheet(item: $activeDueDatePicker) { mode in
                DueDatePickerSheet(mode: mode, dueDate: $dueDate)
                    .presentationDetents([mode.presentationDetent])
                    .presentationDragIndicator(.visible)
                    .presentationBackground(LifeTrackTheme.ColorPalette.backgroundBottom)
            }
            .onDisappear {
                voiceInput.stopRecording()

                if !didSave && documentStorageName != originalDocumentStorageName {
                    DocumentStore.delete(storageName: documentStorageName)
                }
            }
            .onChange(of: voiceInput.transcript) { _, newTranscript in
                voiceTranscript = newTranscript
                applyVoiceTranscript(newTranscript)
            }
            .onAppear {
                if autoStartVoice && !didAutoStartVoice {
                    didAutoStartVoice = true
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.35) {
                        if !voiceInput.isRecording {
                            voiceInput.toggleRecording()
                        }
                    }
                }
            }
        }
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(existingTask == nil ? "New Task" : "Edit Task")
                .font(.system(.title, design: LifeTrackAppTheme.current.fontDesign, weight: .bold))
                .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

            Text(existingTask == nil ? "Capture the next step with enough context to act on it." : "Refine the details and keep reminders accurate.")
                .font(.subheadline)
                .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    private var taskCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Task Details", subtitle: "Name it clearly and classify it.")

            VStack(alignment: .leading, spacing: 7) {
                Text("Title")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                ZStack(alignment: .leading) {
                    if title.isEmpty {
                        Text("e.g. Send quarterly insurance update")
                            .font(.title3.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.placeholderText)
                            .padding(.horizontal, 14)
                            .allowsHitTesting(false)
                    }

                    TextField("", text: $title)
                        .font(.title3.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                        .textInputAutocapitalization(.sentences)
                        .padding(13)
                }
                .background(LifeTrackTheme.ColorPalette.backgroundTop, in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
                .overlay {
                    RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                        .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.9), lineWidth: 0.8)
                }
            }

            VStack(alignment: .leading, spacing: 8) {
                Text("Category")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                LazyVGrid(
                    columns: [GridItem(.adaptive(minimum: 92), spacing: 8, alignment: .leading)],
                    alignment: .leading,
                    spacing: 8
                ) {
                    ForEach(categoryOptions) { option in
                        Button {
                            categoryRawValue = option.id
                            pendingCategoryOption = nil
                        } label: {
                            CategoryChipView(option: option, isSelected: categoryRawValue == option.id)
                        }
                        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                    }
                }

                Button {
                    isShowingCategoryManager = true
                } label: {
                    HStack(spacing: 8) {
                        Image(systemName: "plus")
                        Text("Custom category")
                    }
                    .font(.footnote.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Capsule())
                }
                .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.96))
            }
        }
    }

    private var taskDataShortcutCard: some View {
        SectionCardView {
            SectionHeaderView(
                title: "Task Data",
                subtitle: "Bring tasks in or send your task list out."
            )

            HStack(spacing: LifeTrackTheme.Spacing.small) {
                TaskDataShortcutButton(
                    title: "Import",
                    subtitle: "From file",
                    symbolName: "tray.and.arrow.down",
                    tint: LifeTrackTheme.ColorPalette.accent
                ) {
                    taskDataMode = .importTasks
                    isShowingTaskDataExchange = true
                }

                TaskDataShortcutButton(
                    title: "Export",
                    subtitle: "Share/AirDrop",
                    symbolName: "square.and.arrow.up",
                    tint: LifeTrackTheme.ColorPalette.success
                ) {
                    taskDataMode = .exportTasks
                    isShowingTaskDataExchange = true
                }
            }
        }
    }

    private var voiceCard: some View {
        VoiceInputCard(
            transcript: $voiceTranscript,
            isRecording: voiceInput.isRecording,
            audioLevel: voiceInput.audioLevel,
            feedbackMessage: voiceInput.feedbackMessage,
            authorizationMessage: voiceInput.authorizationMessage,
            onToggleRecording: { voiceInput.toggleRecording() },
            onApplyTranscript: { applyVoiceTranscript(voiceTranscript, force: true) },
            onClearTranscript: {
                voiceInput.clearTranscript()
                voiceTranscript = ""
            }
        )
    }

    private var planningCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Planning", subtitle: "Help LifeTrack choose what matters today.")

            VStack(alignment: .leading, spacing: 8) {
                Text("Priority")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                HStack(spacing: 8) {
                    ForEach(TaskPriority.allCases) { option in
                        Button {
                            priority = option
                        } label: {
                            PriorityPillView(priority: option, isSelected: priority == option)
                        }
                        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                    }
                }
            }

            VStack(alignment: .leading, spacing: 8) {
                Text("Repeat")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                LazyVGrid(
                    columns: [GridItem(.adaptive(minimum: 92), spacing: 8, alignment: .leading)],
                    alignment: .leading,
                    spacing: 8
                ) {
                    ForEach(TaskRecurrence.allCases) { option in
                        Button {
                            recurrence = option
                        } label: {
                            RecurrencePillView(recurrence: option, isSelected: recurrence == option)
                        }
                        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                    }
                }
            }
        }
    }

    private var dateCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Due Date", subtitle: "LifeTrack will schedule a reminder.")

            VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.medium) {
                HStack(spacing: LifeTrackTheme.Spacing.medium) {
                    Image(systemName: "calendar.badge.clock")
                        .font(.system(size: 17, weight: .semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                        .frame(width: LifeTrackTheme.IconSize.largeCircle, height: LifeTrackTheme.IconSize.largeCircle)
                        .background(LifeTrackTheme.ColorPalette.accentSoft, in: Circle())

                    VStack(alignment: .leading, spacing: 3) {
                        Text(dueDate.weekdayDateString)
                            .font(.subheadline.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                            .lineLimit(1)
                            .minimumScaleFactor(0.85)

                        Text(dueDate.timeString)
                            .font(.footnote)
                            .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                            .lineLimit(1)
                    }

                    Spacer(minLength: 0)
                }

                VStack(spacing: 0) {
                    DateSelectionRow(
                        title: "Date",
                        value: dueDate.formatted(Date.FormatStyle().month(.abbreviated).day().year()),
                        symbolName: "calendar",
                        action: { activeDueDatePicker = .date }
                    )

                    Divider()
                        .padding(.leading, 54)

                    DateSelectionRow(
                        title: "Time",
                        value: dueDate.timeString,
                        symbolName: "clock",
                        action: { activeDueDatePicker = .time }
                    )
                }
                .padding(.horizontal, 11)
                .padding(.vertical, 4)
                .background(LifeTrackTheme.ColorPalette.cardElevated.opacity(0.75), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))

                durationSelector
            }
            .padding(11)
            .background(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.85), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous)
                    .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.85), lineWidth: 0.8)
            }
        }
    }

    private var locationCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Location Reminder", subtitle: "Trigger when you arrive or leave a place.")

            if let config = locationConfig {
                HStack(spacing: 12) {
                    Image(systemName: config.onArrival ? "arrow.down.circle.fill" : "arrow.up.circle.fill")
                        .font(.system(size: 20, weight: .semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.accent)

                    VStack(alignment: .leading, spacing: 2) {
                        Text(config.name.isEmpty ? "Selected Place" : config.name)
                            .font(.subheadline.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                            .lineLimit(1)
                        Text("\(config.onArrival ? "On arrival" : "On departure") · \(Int(config.radius))m radius")
                            .font(.caption)
                            .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                    }

                    Spacer()

                    Button {
                        locationConfig = nil
                    } label: {
                        Image(systemName: "xmark.circle.fill")
                            .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                    }
                }

                Button {
                    isShowingLocationPicker = true
                } label: {
                    Text("Change Location")
                        .font(.caption.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                }
            } else {
                Button {
                    isShowingLocationPicker = true
                } label: {
                    HStack(spacing: 10) {
                        Image(systemName: "location.circle.fill")
                            .font(.system(size: 20))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                        Text("Add Location Trigger")
                            .font(.subheadline.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                        Spacer()
                        Image(systemName: "chevron.right")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                    }
                }
                .buttonStyle(.plain)
            }
        }
    }

    private var durationSelector: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: LifeTrackTheme.Spacing.small) {
                Image(systemName: "timer")
                    .font(.system(size: 13, weight: .bold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)

                Text("Duration")
                    .font(.footnote.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                Spacer(minLength: 0)

                Text(durationTitle(for: durationMinutes))
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
            }

            LazyVGrid(
                columns: [GridItem(.adaptive(minimum: 70), spacing: 8, alignment: .leading)],
                alignment: .leading,
                spacing: 8
            ) {
                ForEach(durationOptions, id: \.self) { option in
                    Button {
                        durationMinutes = option
                    } label: {
                        Text(durationTitle(for: option))
                            .font(.caption.weight(.bold))
                            .foregroundStyle(durationMinutes == option ? .white : LifeTrackTheme.ColorPalette.secondaryText)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 8)
                            .background(durationChipBackground(isSelected: durationMinutes == option), in: Capsule())
                            .overlay {
                                Capsule()
                                    .stroke(durationMinutes == option ? Color.white.opacity(0.22) : LifeTrackTheme.ColorPalette.hairline.opacity(0.82), lineWidth: 0.8)
                            }
                    }
                    .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                }
            }
        }
        .padding(11)
        .background(LifeTrackTheme.ColorPalette.cardElevated.opacity(0.66), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
    }

    private var notesCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Notes", subtitle: "Add context, links, or draft text.")

            ZStack(alignment: .topLeading) {
                TextEditor(text: $notes)
                    .font(.body)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                    .frame(minHeight: 126)
                    .scrollContentBackground(.hidden)
                    .padding(9)

                if notes.isEmpty {
                    Text("Write the details that will make this task easier later...")
                        .font(.body)
                        .foregroundStyle(LifeTrackTheme.ColorPalette.placeholderText)
                        .padding(.horizontal, 16)
                        .padding(.vertical, 18)
                        .allowsHitTesting(false)
                }
            }
            .background(LifeTrackTheme.ColorPalette.backgroundTop, in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                    .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.9), lineWidth: 0.8)
            }
        }
    }

    private var documentCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Document", subtitle: "Scan a document or attach a file stored locally with this task.")

            HStack(spacing: LifeTrackTheme.Spacing.small) {
                DocumentCaptureButton(
                    title: "Scan",
                    subtitle: "Use camera",
                    symbolName: "doc.viewfinder",
                    tint: LifeTrackTheme.ColorPalette.accent,
                    isAvailable: DocumentScanAvailability.isSupported
                ) {
                    isScanningDocument = true
                }

                DocumentCaptureButton(
                    title: "Attach",
                    subtitle: "From files",
                    symbolName: "paperclip",
                    tint: LifeTrackTheme.ColorPalette.success,
                    isAvailable: true
                ) {
                    isImportingDocument = true
                }
            }

            AttachmentButton(
                documentDisplayName: documentDisplayName,
                onAttach: { isImportingDocument = true },
                onRemove: documentDisplayName == nil ? nil : { removeDocument() }
            )

            if let documentError {
                Text(documentError)
                    .font(.footnote.weight(.medium))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.danger)
            }

            if isAnalyzingDocument {
                HStack(spacing: LifeTrackTheme.Spacing.small) {
                    ProgressView()
                        .tint(LifeTrackTheme.ColorPalette.accent)

                    Text("Reading document locally...")
                        .font(.footnote.weight(.medium))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }
                .padding(11)
                .background(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.86), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
            } else if hasDocumentAnalysis {
                DocumentIntelligenceView(
                    summary: documentAnalysisSummary,
                    suggestedTitle: documentSuggestedTitle,
                    suggestedDueDate: documentSuggestedDueDate,
                    keywords: documentKeywords,
                    extractedText: documentExtractedText,
                    hasApplied: didApplyDocumentSuggestion,
                    onApplySuggestion: applyDocumentSuggestion
                )
            }
        }
    }

    private var templateActionCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Template Action", subtitle: "This shortcut stays attached to the task.")

            HStack(spacing: LifeTrackTheme.Spacing.medium) {
                Image(systemName: "envelope.badge")
                    .font(.system(size: 17, weight: .semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .frame(width: LifeTrackTheme.IconSize.largeCircle, height: LifeTrackTheme.IconSize.largeCircle)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Circle())

                VStack(alignment: .leading, spacing: 4) {
                    Text("Email draft")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                    Text("Open a pre-filled email from the task detail screen.")
                        .font(.footnote)
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }
            }
        }
    }

    private var statusCard: some View {
        SectionCardView {
            Toggle(isOn: $isCompleted) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Completed")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                    Text("Completed tasks will not schedule reminders.")
                        .font(.footnote)
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }
            }
            .tint(LifeTrackTheme.ColorPalette.success)
        }
    }

    private var canSave: Bool {
        !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private var categoryOptions: [TaskCategoryOption] {
        TaskCategoryOption.all(customCategories: customCategories)
    }

    private var selectedCategoryOption: TaskCategoryOption {
        if let pendingCategoryOption, pendingCategoryOption.id == categoryRawValue {
            return pendingCategoryOption
        }

        return TaskCategoryOption.resolved(rawValue: categoryRawValue, customCategories: customCategories)
    }

    private func removeDocument() {
        if documentStorageName != originalDocumentStorageName {
            DocumentStore.delete(storageName: documentStorageName)
        }
        documentStorageName = nil
        documentDisplayName = nil
        clearDocumentAnalysis()

        if notes == lastAutoGeneratedDocumentNotes {
            notes = ""
        }
        lastAutoGeneratedDocumentNotes = ""
    }

    private func handleScanResult(_ result: Result<URL, Error>) {
        switch result {
        case .success(let url):
            defer { try? FileManager.default.removeItem(at: url) }

            do {
                let pendingDocumentStorageName = documentStorageName
                let storedDocument = try DocumentStore.saveSecurityScopedFile(from: url)
                if pendingDocumentStorageName != originalDocumentStorageName {
                    DocumentStore.delete(storageName: pendingDocumentStorageName)
                }
                documentStorageName = storedDocument.storageName
                documentDisplayName = storedDocument.displayName
                documentError = nil
                analyzeDocument(storageName: storedDocument.storageName, displayName: storedDocument.displayName)
                LifeTrackHaptics.lightImpact()
            } catch {
                documentError = "Scan could not be saved."
                isAnalyzingDocument = false
            }
        case .failure(let error):
            if case DocumentScannerView.ScanError.cancelled = error {
                return
            }
            documentError = "Scan could not be completed."
            isAnalyzingDocument = false
        }
    }

    private func handleDocumentImport(_ result: Result<[URL], Error>) {
        switch result {
        case .success(let urls):
            guard let url = urls.first else {
                return
            }

            do {
                let pendingDocumentStorageName = documentStorageName
                let storedDocument = try DocumentStore.saveSecurityScopedFile(from: url)
                if pendingDocumentStorageName != originalDocumentStorageName {
                    DocumentStore.delete(storageName: pendingDocumentStorageName)
                }
                documentStorageName = storedDocument.storageName
                documentDisplayName = storedDocument.displayName
                documentError = nil
                analyzeDocument(storageName: storedDocument.storageName, displayName: storedDocument.displayName)
            } catch {
                documentError = "Document could not be attached."
                isAnalyzingDocument = false
            }
        case .failure:
            documentError = "Document could not be attached."
            isAnalyzingDocument = false
        }
    }

    private func analyzeDocument(storageName: String, displayName: String) {
        guard let url = DocumentStore.url(for: storageName) else {
            clearDocumentAnalysis()
            documentError = "Document was attached, but could not be read yet."
            return
        }

        clearDocumentAnalysis()
        isAnalyzingDocument = true

        Task {
            let result = await DocumentAnalysisManager.analyze(url: url, displayName: displayName)
            await MainActor.run {
                guard documentStorageName == storageName else {
                    return
                }

                documentExtractedText = result.extractedText
                documentAnalysisSummary = result.summary
                documentSuggestedTitle = result.suggestedTitle
                documentSuggestedDueDate = result.suggestedDueDate
                documentKeywords = result.keywords
                isAnalyzingDocument = false

                applyAutoGeneratedDocumentNotes(displayName: displayName, result: result)
            }
        }
    }

    private func applyAutoGeneratedDocumentNotes(displayName: String, result: DocumentAnalysisResult) {
        let autoNotes = buildAutoDocumentNotes(displayName: displayName, result: result)
        guard !autoNotes.isEmpty else { return }

        let trimmed = notes.trimmingCharacters(in: .whitespacesAndNewlines)

        if trimmed.isEmpty || notes == lastAutoGeneratedDocumentNotes {
            notes = autoNotes
            lastAutoGeneratedDocumentNotes = autoNotes
        }
    }

    private func buildAutoDocumentNotes(displayName: String, result: DocumentAnalysisResult) -> String {
        var lines: [String] = ["Attached: \(displayName)"]

        if !result.keywords.isEmpty {
            lines.append("Detected: \(result.keywords.prefix(5).joined(separator: ", "))")
        }

        if let suggestedDueDate = result.suggestedDueDate {
            lines.append("Date found: \(suggestedDueDate.weekdayDateString)")
        }

        let excerpt = documentExcerpt(from: result.extractedText)
        if !excerpt.isEmpty {
            lines.append("")
            lines.append(excerpt)
        }

        return lines.joined(separator: "\n")
    }

    private func documentExcerpt(from text: String) -> String {
        let normalized = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else { return "" }

        let maxLength = 240
        if normalized.count <= maxLength {
            return normalized
        }

        let clipped = normalized.prefix(maxLength)
        if let lastSpace = clipped.lastIndex(of: " ") {
            return clipped[..<lastSpace] + "…"
        }

        return clipped + "…"
    }

    private func clearDocumentAnalysis() {
        documentExtractedText = ""
        documentAnalysisSummary = nil
        documentSuggestedTitle = nil
        documentSuggestedDueDate = nil
        documentKeywords = []
        didApplyDocumentSuggestion = false
    }

    private var hasDocumentAnalysis: Bool {
        documentAnalysisSummary != nil ||
            documentSuggestedTitle != nil ||
            documentSuggestedDueDate != nil ||
            !documentKeywords.isEmpty ||
            !documentExtractedText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func applyDocumentSuggestion() {
        var didChange = false

        if let suggestedTitle = documentSuggestedTitle, !suggestedTitle.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            withAnimation(.easeOut(duration: 0.2)) {
                title = suggestedTitle
            }
            didChange = true
        }

        if let documentSuggestedDueDate {
            withAnimation(.easeOut(duration: 0.2)) {
                dueDate = documentSuggestedDueDate
            }
            didChange = true
        }

        if documentKeywords.contains("insurance") || documentKeywords.contains("invoice") || documentKeywords.contains("bill") || documentKeywords.contains("tax") {
            categoryRawValue = TaskCategory.finance.rawValue
            pendingCategoryOption = nil
            didChange = true
        } else if documentKeywords.contains("appointment") || documentKeywords.contains("medical") {
            categoryRawValue = TaskCategory.health.rawValue
            pendingCategoryOption = nil
            didChange = true
        } else if documentKeywords.contains("school") || documentKeywords.contains("application") {
            categoryRawValue = TaskCategory.personal.rawValue
            pendingCategoryOption = nil
            didChange = true
        }

        if didChange {
            LifeTrackHaptics.lightImpact()
            withAnimation(.easeOut(duration: 0.22)) {
                didApplyDocumentSuggestion = true
            }
            documentScrollRequest = UUID()
        }
    }

    private func applyVoiceTranscript(_ transcript: String, force: Bool = false) {
        let cleanedTranscript = transcript.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleanedTranscript.isEmpty else {
            return
        }

        let draft = VoiceTaskParser.parse(cleanedTranscript)

        if let draftTitle = draft.title, force || title.isEmpty || title == lastVoiceGeneratedTitle {
            title = draftTitle
            lastVoiceGeneratedTitle = draftTitle
        }

        if let draftCategory = draft.category, force || !didApplyVoiceCategory {
            categoryRawValue = draftCategory.rawValue
            pendingCategoryOption = nil
            didApplyVoiceCategory = true
        }

        if let draftDueDate = draft.dueDate, force || !didApplyVoiceDueDate {
            dueDate = draftDueDate
            didApplyVoiceDueDate = true
        }

        let trimmedNotes = notes.trimmingCharacters(in: .whitespacesAndNewlines)
        let notesIsOverridableByVoice =
            trimmedNotes.isEmpty ||
            notes == lastVoiceGeneratedNotes ||
            (trimmedNotes == lastAutoGeneratedDocumentNotes.trimmingCharacters(in: .whitespacesAndNewlines) && !lastAutoGeneratedDocumentNotes.isEmpty)

        if let draftNotes = draft.notes, !draftNotes.isEmpty, force || notesIsOverridableByVoice {
            notes = draftNotes
            lastVoiceGeneratedNotes = draftNotes
        } else if draft.notes == nil, notes == lastVoiceGeneratedNotes, !lastVoiceGeneratedNotes.isEmpty {
            notes = ""
            lastVoiceGeneratedNotes = ""
        }
    }

    private func save() {
        let cleanedTitle = title.trimmingCharacters(in: .whitespacesAndNewlines)
        let now = Date()
        let wasCompleted = existingTask?.isCompleted ?? false

        let task: LifeTask
        if let existingTask {
            task = existingTask
            if originalDocumentStorageName != documentStorageName {
                DocumentStore.delete(storageName: originalDocumentStorageName)
            }
            task.title = cleanedTitle
            task.categoryRawValue = categoryRawValue
            task.dueDate = dueDate
            task.isCompleted = isCompleted
            task.notes = notes
            task.templateAction = templateAction
            task.priority = priority
            task.recurrence = recurrence
            task.scheduledDurationMinutes = durationMinutes
            task.documentStorageName = documentStorageName
            task.documentDisplayName = documentDisplayName
            task.documentExtractedText = documentExtractedText
            task.documentAnalysisSummary = documentAnalysisSummary
            task.documentSuggestedTitle = documentSuggestedTitle
            task.documentSuggestedDueDate = documentSuggestedDueDate
            task.documentKeywords = documentKeywords
            task.locationReminderName = locationConfig?.name
            task.locationReminderLatitude = locationConfig?.latitude
            task.locationReminderLongitude = locationConfig?.longitude
            task.locationReminderRadius = locationConfig?.radius
            task.locationReminderOnArrival = locationConfig?.onArrival ?? true
            task.updatedAt = now
        } else {
            task = LifeTask(
                title: cleanedTitle,
                category: selectedCategory,
                categoryRawValue: categoryRawValue,
                dueDate: dueDate,
                isCompleted: isCompleted,
                notes: notes,
                templateAction: templateAction,
                priority: priority,
                recurrence: recurrence,
                estimatedDurationMinutes: durationMinutes,
                documentStorageName: documentStorageName,
                documentDisplayName: documentDisplayName,
                documentExtractedText: documentExtractedText,
                documentAnalysisSummary: documentAnalysisSummary,
                documentSuggestedTitle: documentSuggestedTitle,
                documentSuggestedDueDate: documentSuggestedDueDate,
                documentKeywords: documentKeywords,
                createdAt: now,
                updatedAt: now
            )
            task.locationReminderName = locationConfig?.name
            task.locationReminderLatitude = locationConfig?.latitude
            task.locationReminderLongitude = locationConfig?.longitude
            task.locationReminderRadius = locationConfig?.radius
            task.locationReminderOnArrival = locationConfig?.onArrival ?? true
            if task.isHabit { task.habitGroupID = task.id }
            modelContext.insert(task)
        }

        let nextRecurringTask: LifeTask?
        if !wasCompleted && task.isCompleted {
            nextRecurringTask = task.nextRecurringTask(completedAt: now)
            if let nextRecurringTask {
                modelContext.insert(nextRecurringTask)
            }
        } else {
            nextRecurringTask = nil
        }

        try? modelContext.save()
        ReminderScheduler.synchronizeReminder(
            taskID: task.id,
            title: task.title,
            categoryTitle: selectedCategoryOption.title,
            dueDate: task.dueDate,
            isCompleted: task.isCompleted
        )
        if let nextRecurringTask {
            TaskLifecycleManager.synchronizeReminder(
                for: nextRecurringTask,
                customCategories: customCategories
            )
        }
        LocationReminderManager.shared.cancelRegion(for: task.id)
        if task.hasLocationReminder && !task.isCompleted {
            LocationReminderManager.shared.scheduleRegion(for: task)
        }
        didSave = true
        dismiss()
    }

    private var selectedCategory: TaskCategory {
        TaskCategory(rawValue: categoryRawValue) ?? .other
    }

    private func durationTitle(for minutes: Int) -> String {
        if minutes < 60 {
            return "\(minutes)m"
        }

        let hours = minutes / 60
        let remainingMinutes = minutes % 60
        if remainingMinutes == 0 {
            return "\(hours)h"
        }

        return "\(hours)h \(remainingMinutes)m"
    }

    private func durationChipBackground(isSelected: Bool) -> some ShapeStyle {
        if isSelected {
            return AnyShapeStyle(LifeTrackTheme.ColorPalette.accentGradient)
        }

        return AnyShapeStyle(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.86))
    }
}

private enum NewTaskViewAnchor: Hashable {
    case taskCard
}

private enum DueDatePickerMode: String, Identifiable {
    case date
    case time

    var id: String { rawValue }

    var title: String {
        switch self {
        case .date: "Choose Date"
        case .time: "Choose Time"
        }
    }

    var subtitle: String {
        switch self {
        case .date: "Pick a reminder day."
        case .time: "Set the task time."
        }
    }

    var symbolName: String {
        switch self {
        case .date: "calendar"
        case .time: "clock"
        }
    }

    var presentationDetent: PresentationDetent {
        switch self {
        case .date: .height(590)
        case .time: .height(450)
        }
    }
}

private struct DateSelectionRow: View {
    let title: String
    let value: String
    let symbolName: String
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            HStack(spacing: LifeTrackTheme.Spacing.medium) {
                Image(systemName: symbolName)
                    .font(.system(size: 13, weight: .bold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .frame(width: 32, height: 32)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Circle())

                Text(title)
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                Spacer(minLength: LifeTrackTheme.Spacing.medium)

                Text(value)
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .lineLimit(1)
                    .minimumScaleFactor(0.78)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(LifeTrackTheme.ColorPalette.accentSoft.opacity(0.72), in: Capsule())

                Image(systemName: "chevron.right")
                    .font(.system(size: 12, weight: .bold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.tertiaryText)
            }
            .frame(minHeight: 50)
        }
        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.985, pressedOpacity: 0.94))
    }
}

private struct DueDatePickerSheet: View {
    let mode: DueDatePickerMode
    @Binding var dueDate: Date
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        ZStack {
            LifeTrackTheme.appBackground
                .ignoresSafeArea()

            VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.large) {
                sheetHeader

                if mode == .date {
                    themedDatePicker
                } else {
                    themedTimePicker
                }
            }
            .padding(.horizontal, LifeTrackTheme.Spacing.xLarge)
            .padding(.top, LifeTrackTheme.Spacing.medium)
            .padding(.bottom, LifeTrackTheme.Spacing.xLarge)
        }
    }

    private var sheetHeader: some View {
        HStack(alignment: .center, spacing: LifeTrackTheme.Spacing.medium) {
            Image(systemName: mode.symbolName)
                .font(.system(size: 16, weight: .bold))
                .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                .frame(width: 44, height: 44)
                .background(LifeTrackTheme.ColorPalette.accentSoft, in: Circle())

            VStack(alignment: .leading, spacing: 3) {
                Text(mode.title)
                    .font(.system(.title3, design: LifeTrackAppTheme.current.fontDesign, weight: .bold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                    .lineLimit(1)

                Text(mode.subtitle)
                    .font(.subheadline.weight(.medium))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                    .lineLimit(1)
                    .minimumScaleFactor(0.85)
            }

            Spacer(minLength: LifeTrackTheme.Spacing.small)

            Button("Done") {
                dismiss()
            }
            .font(.callout.weight(.bold))
            .foregroundStyle(.white)
            .padding(.horizontal, 16)
            .padding(.vertical, 10)
            .background(LifeTrackTheme.ColorPalette.accentGradient, in: Capsule())
            .shadow(color: LifeTrackTheme.ColorPalette.accent.opacity(0.18), radius: 10, x: 0, y: 6)
            .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.96, pressedOpacity: 0.94))
        }
    }

    private var themedDatePicker: some View {
        VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.medium) {
            HStack {
                Text(dueDate.weekdayDateString)
                    .font(.headline.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                Spacer(minLength: LifeTrackTheme.Spacing.medium)

                Text(dueDate.formatted(Date.FormatStyle().year()))
                    .font(.footnote.weight(.bold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .padding(.horizontal, 10)
                    .padding(.vertical, 6)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Capsule())
            }

            DatePicker("", selection: $dueDate, displayedComponents: .date)
                .labelsHidden()
                .datePickerStyle(.graphical)
                .tint(LifeTrackTheme.ColorPalette.accent)
                .padding(10)
                .environment(\.colorScheme, .light)
                .background(Color.white.opacity(0.96), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous))
                .overlay {
                    RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous)
                        .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.82), lineWidth: 0.8)
                }
                .shadow(color: LifeTrackTheme.ColorPalette.shadow.opacity(0.08), radius: 14, x: 0, y: 8)

            HStack(spacing: 8) {
                DateShortcutChip(title: "Today", isSelected: isSelectedDate(offset: 0)) {
                    setDate(offset: 0)
                }
                DateShortcutChip(title: "Tomorrow", isSelected: isSelectedDate(offset: 1)) {
                    setDate(offset: 1)
                }
                DateShortcutChip(title: "Next Week", isSelected: isSelectedDate(offset: 7)) {
                    setDate(offset: 7)
                }
            }
        }
        .lifeTrackCard(padding: LifeTrackTheme.Spacing.medium, backgroundColor: LifeTrackTheme.ColorPalette.card)
    }

    private var themedTimePicker: some View {
        VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.medium) {
            HStack {
                VStack(alignment: .leading, spacing: 3) {
                    Text("Reminder time")
                        .font(.headline.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                    Text("Due at \(dueDate.timeString)")
                        .font(.footnote.weight(.medium))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }

                Spacer(minLength: LifeTrackTheme.Spacing.medium)

                Text(dueDate.timeString)
                    .font(.title3.monospacedDigit().weight(.bold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .padding(.horizontal, 14)
                    .padding(.vertical, 9)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Capsule())
            }

            DatePicker("", selection: $dueDate, displayedComponents: .hourAndMinute)
                .labelsHidden()
                .datePickerStyle(.wheel)
                .tint(LifeTrackTheme.ColorPalette.accent)
                .frame(maxWidth: .infinity)
                .frame(height: 170)
                .clipped()
                .environment(\.colorScheme, .light)
                .background(Color.white.opacity(0.96), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous))
                .overlay {
                    RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous)
                        .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.82), lineWidth: 0.8)
                }
                .shadow(color: LifeTrackTheme.ColorPalette.shadow.opacity(0.08), radius: 14, x: 0, y: 8)

            HStack(spacing: 8) {
                DateShortcutChip(title: "09:00", isSelected: isSelectedTime(hour: 9, minute: 0)) {
                    setTime(hour: 9, minute: 0)
                }
                DateShortcutChip(title: "14:00", isSelected: isSelectedTime(hour: 14, minute: 0)) {
                    setTime(hour: 14, minute: 0)
                }
                DateShortcutChip(title: "18:00", isSelected: isSelectedTime(hour: 18, minute: 0)) {
                    setTime(hour: 18, minute: 0)
                }
            }
        }
        .lifeTrackCard(padding: LifeTrackTheme.Spacing.medium, backgroundColor: LifeTrackTheme.ColorPalette.card)
    }

    private func setDate(offset: Int) {
        let calendar = Calendar.current
        guard let targetDay = calendar.date(byAdding: .day, value: offset, to: Date()) else {
            return
        }

        let time = calendar.dateComponents([.hour, .minute, .second], from: dueDate)
        dueDate = calendar.date(
            bySettingHour: time.hour ?? 9,
            minute: time.minute ?? 0,
            second: time.second ?? 0,
            of: targetDay
        ) ?? dueDate
    }

    private func setTime(hour: Int, minute: Int) {
        dueDate = Calendar.current.date(
            bySettingHour: hour,
            minute: minute,
            second: 0,
            of: dueDate
        ) ?? dueDate
    }

    private func isSelectedDate(offset: Int) -> Bool {
        guard let targetDay = Calendar.current.date(byAdding: .day, value: offset, to: Date()) else {
            return false
        }

        return Calendar.current.isDate(dueDate, inSameDayAs: targetDay)
    }

    private func isSelectedTime(hour: Int, minute: Int) -> Bool {
        let components = Calendar.current.dateComponents([.hour, .minute], from: dueDate)
        return components.hour == hour && components.minute == minute
    }
}

private struct DateShortcutChip: View {
    let title: String
    let isSelected: Bool
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Text(title)
                .font(.caption.weight(.bold))
                .foregroundStyle(isSelected ? .white : LifeTrackTheme.ColorPalette.secondaryText)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 9)
                .background(
                    isSelected ? AnyShapeStyle(LifeTrackTheme.ColorPalette.accentGradient) : AnyShapeStyle(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.84)),
                    in: Capsule()
                )
                .overlay {
                    Capsule()
                        .stroke(isSelected ? Color.white.opacity(0.22) : LifeTrackTheme.ColorPalette.hairline.opacity(0.82), lineWidth: 0.8)
                }
        }
        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.96, pressedOpacity: 0.92))
    }
}

private struct TaskDataShortcutButton: View {
    let title: String
    let subtitle: String
    let symbolName: String
    let tint: Color
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            HStack(spacing: 9) {
                Image(systemName: symbolName)
                    .font(.system(size: 14, weight: .bold))
                    .foregroundStyle(tint)
                    .frame(width: 32, height: 32)
                    .background(tint.opacity(0.12), in: Circle())

                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                        .lineLimit(1)

                    Text(subtitle)
                        .font(.caption2.weight(.medium))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                        .lineLimit(1)
                }

                Spacer(minLength: 0)
            }
            .padding(11)
            .frame(maxWidth: .infinity, minHeight: 58)
            .background(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.82), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                    .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.82), lineWidth: 0.8)
            }
        }
        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.97, pressedOpacity: 0.93))
    }
}

private struct DocumentIntelligenceView: View {
    let summary: String?
    let suggestedTitle: String?
    let suggestedDueDate: Date?
    let keywords: [String]
    let extractedText: String
    let hasApplied: Bool
    let onApplySuggestion: () -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.small) {
            HStack(alignment: .top, spacing: LifeTrackTheme.Spacing.medium) {
                Image(systemName: "doc.text.magnifyingglass")
                    .font(.system(size: 17, weight: .semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .frame(width: LifeTrackTheme.IconSize.largeCircle, height: LifeTrackTheme.IconSize.largeCircle)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Circle())

                VStack(alignment: .leading, spacing: 5) {
                    Text("Document Assistant")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                    Text(summary ?? "Searchable document text is saved locally.")
                        .font(.footnote)
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }

            if let suggestedTitle {
                DocumentSuggestionRow(
                    symbolName: "sparkles",
                    title: suggestedTitle,
                    subtitle: suggestedDueDate.map { "Suggested due date: \($0.weekdayDateString)" } ?? "Suggested from the uploaded file."
                )

                if hasApplied {
                    HStack(spacing: 8) {
                        Image(systemName: "checkmark.seal.fill")
                            .font(.callout.weight(.semibold))
                        Text("Suggestion applied to task")
                            .font(.callout.weight(.semibold))
                    }
                    .foregroundStyle(LifeTrackTheme.ColorPalette.success)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 12)
                    .background(
                        LifeTrackTheme.ColorPalette.success.opacity(0.12),
                        in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                    )
                    .transition(.opacity.combined(with: .scale(scale: 0.98)))
                } else {
                    LifeTrackPrimaryButton(
                        title: "Apply Document Suggestion",
                        systemImage: "wand.and.stars",
                        action: onApplySuggestion
                    )
                }
            }

            if !keywords.isEmpty {
                ScrollView(.horizontal) {
                    HStack(spacing: 7) {
                        ForEach(keywords.prefix(6), id: \.self) { keyword in
                            Text(keyword.capitalized)
                                .font(.caption.weight(.semibold))
                                .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                                .padding(.horizontal, 9)
                                .padding(.vertical, 5)
                                .background(LifeTrackTheme.ColorPalette.accentSoft, in: Capsule())
                        }
                    }
                }
                .scrollIndicators(.hidden)
            }

            if !extractedText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                Text(extractedText)
                    .font(.caption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                    .lineLimit(3)
                    .padding(10)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.86), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
            }
        }
        .padding(12)
        .background(LifeTrackTheme.ColorPalette.accentSoft.opacity(0.48), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous))
        .overlay {
            RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.card, style: .continuous)
                .stroke(LifeTrackTheme.ColorPalette.accent.opacity(0.18), lineWidth: 0.8)
        }
    }
}

private struct DocumentSuggestionRow: View {
    let symbolName: String
    let title: String
    let subtitle: String

    var body: some View {
        HStack(spacing: LifeTrackTheme.Spacing.small) {
            Image(systemName: symbolName)
                .font(.system(size: 14, weight: .bold))
                .foregroundStyle(LifeTrackTheme.ColorPalette.warning)
                .frame(width: 30, height: 30)
                .background(LifeTrackTheme.ColorPalette.warning.opacity(0.12), in: Circle())

            VStack(alignment: .leading, spacing: 3) {
                Text(title)
                    .font(.footnote.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                    .lineLimit(2)

                Text(subtitle)
                    .font(.caption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                    .lineLimit(2)
            }

            Spacer(minLength: 0)
        }
        .padding(10)
        .background(LifeTrackTheme.ColorPalette.cardElevated.opacity(0.86), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
    }
}

private struct DocumentCaptureButton: View {
    let title: String
    let subtitle: String
    let symbolName: String
    let tint: Color
    let isAvailable: Bool
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            HStack(spacing: 9) {
                Image(systemName: symbolName)
                    .font(.system(size: 15, weight: .bold))
                    .foregroundStyle(tint)
                    .frame(width: 34, height: 34)
                    .background(tint.opacity(0.12), in: Circle())

                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                        .lineLimit(1)

                    Text(isAvailable ? subtitle : "Unavailable")
                        .font(.caption2.weight(.medium))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                        .lineLimit(1)
                }

                Spacer(minLength: 0)
            }
            .padding(11)
            .frame(maxWidth: .infinity, minHeight: 58)
            .background(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.82), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                    .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.82), lineWidth: 0.8)
            }
            .opacity(isAvailable ? 1 : 0.5)
        }
        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.97, pressedOpacity: 0.93))
        .disabled(!isAvailable)
    }
}

enum DocumentScanAvailability {
    static var isSupported: Bool {
        VNDocumentCameraViewController.isSupported
    }
}

#Preview("New Task") {
    let configuration = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(for: LifeTask.self, CustomTaskCategory.self, configurations: configuration)

    return NewTaskView(template: TaskTemplate.common.first)
        .modelContainer(container)
}
