//
//  NewTaskView.swift
//  LifeTrack
//
//  Created by Halalisani Mbanjwa on 2026/04/18.
//

import SwiftData
import SwiftUI
import UniformTypeIdentifiers
import VisionKit

struct NewTaskView: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext
    @Query(sort: \CustomTaskCategory.title) private var customCategories: [CustomTaskCategory]

    @StateObject private var voiceInput = VoiceTaskInputManager()
    @StateObject private var voiceEnhancer = AIVoiceTaskEnhancer()

    private let existingTask: LifeTask?
    private let originalDocumentStorageName: String?
    private let autoStartVoice: Bool
    private let isFreshNewTask: Bool
    @State private var didAutoStartVoice = false
    @State private var isShowingResumePrompt = false
    @State private var pendingDraft: NewTaskDraft?
    @State private var didOfferDraftResume = false

    @State private var form: NewTaskFormState
    @State private var isImportingDocument = false
    @State private var isScanningDocument = false
    @State private var isAnalyzingDocument = false
    @State private var isShowingCategoryManager = false
    @State private var activeDueDatePicker: DueDatePickerMode?
    @State private var pendingCategoryOption: TaskCategoryOption?
    @State private var documentError: String?
    @State private var didSave = false
    @State private var lastVoiceGeneratedTitle = ""
    @State private var lastVoiceGeneratedNotes = ""
    @State private var didApplyVoiceCategory = false
    @State private var didApplyVoiceDueDate = false
    @State private var didApplyDocumentSuggestion = false
    @State private var documentScrollRequest: UUID?
    @State private var lastAutoGeneratedDocumentNotes = ""
    @State private var isShowingLocationPicker = false
    @State private var isAIEnhancing = false
    @State private var isShowingVoiceTranscriptDisclosure = false
    @AppStorage(LifeTrackSettings.Keys.voiceTranscriptDisclosureShown) private var voiceTranscriptDisclosureShown = false
    @State private var isAdvancedExpanded = false
    @EnvironmentObject private var subscriptionManager: SubscriptionManager

    private static var currentMoneyCurrencyCode: String {
        MoneyCurrency.normalized(UserDefaults.standard.string(forKey: LifeTrackSettings.Keys.moneyCurrencyCode) ?? MoneyCurrency.defaultCode)
    }

    init(task: LifeTask? = nil, template: TaskTemplate? = nil, captureDraft: CapturedTaskDraft? = nil, autoStartVoice: Bool = false) {
        existingTask = task
        originalDocumentStorageName = task?.documentStorageName
        self.autoStartVoice = autoStartVoice
        self.isFreshNewTask = (task == nil && template == nil && captureDraft == nil)
        _form = State(wrappedValue: NewTaskFormState(task: task, template: template, captureDraft: captureDraft))
    }

    var body: some View {
        NavigationStack {
            ZStack {
                LifeTrackTheme.appBackground
                    .ignoresSafeArea()

                ScrollViewReader { scrollProxy in
                    ScrollView {
                        VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.large) {
                            header

                            voiceCard
                                .id(NewTaskViewAnchor.voiceCard)

                            taskCard
                                .id(NewTaskViewAnchor.taskCard)

                            planningCard

                            TaskDateCard(form: form, activeDueDatePicker: $activeDueDatePicker)

                            financialDetailsCard

                            if subscriptionManager.tier >= .standard {
                                TaskLocationCard(form: form, isShowingLocationPicker: $isShowingLocationPicker)
                            }

                            TaskNotesCard(form: form)

                            advancedFieldsCard

                            documentCard

                        if form.templateAction == .email {
                            templateActionCard
                        }

                        if existingTask != nil {
                            TaskStatusCard(form: form)
                        }
                    }
                        .padding(.horizontal, LifeTrackTheme.Spacing.xLarge)
                        .padding(.top, LifeTrackTheme.Spacing.medium)
                        .padding(.bottom, 112)
                    }
                    .scrollIndicators(.hidden)
                    .onChange(of: documentScrollRequest) { _, newValue in
                        guard newValue != nil else { return }
                        withAnimation(.easeOut(duration: 0.28)) {
                            scrollProxy.scrollTo(NewTaskViewAnchor.taskCard, anchor: .top)
                        }
                        documentScrollRequest = nil
                    }
                    .overlay(alignment: .bottomTrailing) {
                        VoiceFloatingButton(isRecording: voiceInput.isRecording) {
                            handleFloatingVoiceButtonTap(scrollProxy: scrollProxy)
                        }
                        .padding(.trailing, LifeTrackTheme.Spacing.xLarge)
                        .padding(.bottom, LifeTrackTheme.Spacing.xxLarge)
                    }
                }
            }
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button("Save", action: save)
                        .fontWeight(.semibold)
                        .disabled(!canSave)
                }
            }
            .fileImporter(
                isPresented: $isImportingDocument,
                allowedContentTypes: [.item],
                allowsMultipleSelection: false,
                onCompletion: handleDocumentImport
            )
            .fullScreenCover(isPresented: $isScanningDocument) {
                DocumentScannerView { result in
                    isScanningDocument = false
                    handleScanResult(result)
                }
                .ignoresSafeArea()
            }
            .sheet(isPresented: $isShowingLocationPicker) {
                LocationPickerView { config in
                    form.locationConfig = config
                }
                .presentationDetents([.large])
                .presentationDragIndicator(.visible)
            }
            .sheet(isPresented: $isShowingCategoryManager) {
                CategoryManagerView { option in
                    form.categoryRawValue = option.id
                    pendingCategoryOption = option
                }
                .presentationDetents([.large])
                .presentationDragIndicator(.visible)
            }
            .sheet(item: $activeDueDatePicker) { mode in
                DueDatePickerSheet(mode: mode, dueDate: $form.dueDate)
                    .presentationDetents([mode.presentationDetent])
                    .presentationDragIndicator(.visible)
                    .presentationBackground(LifeTrackTheme.ColorPalette.backgroundBottom)
            }
            .onDisappear {
                voiceInput.stopRecording()

                if !didSave && form.documentStorageName != originalDocumentStorageName {
                    DocumentStore.delete(storageName: form.documentStorageName)
                }

                if isFreshNewTask && !didSave {
                    persistDraftIfMeaningful()
                }
            }
            .onChange(of: voiceInput.transcript) { _, newTranscript in
                form.voiceTranscript = newTranscript
                applyVoiceTranscript(newTranscript)
            }
            .onChange(of: form.dueDate) { _, newDueDate in
                if !form.hasPaymentDate {
                    form.paymentDate = newDueDate
                }
            }
            .onChange(of: voiceInput.isRecording) { wasRecording, isNowRecording in
                if wasRecording && !isNowRecording,
                   !form.voiceTranscript.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                   subscriptionManager.tier >= .ultimate,
                   voiceEnhancer.isConfigured {
                    Task { await enhanceVoiceDraftWithAI() }
                }
            }
            .onAppear {
                if autoStartVoice && !didAutoStartVoice {
                    didAutoStartVoice = true
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.35) {
                        if !voiceInput.isRecording {
                            voiceInput.toggleRecording()
                        }
                    }
                }

                if isFreshNewTask && !didOfferDraftResume,
                   let draft = NewTaskDraftStore.load() {
                    didOfferDraftResume = true
                    pendingDraft = draft
                    isShowingResumePrompt = true
                }
            }
            .confirmationDialog(
                "Resume previous task?",
                isPresented: $isShowingResumePrompt,
                titleVisibility: .visible,
                presenting: pendingDraft
            ) { draft in
                Button("Resume") {
                    apply(draft: draft)
                    pendingDraft = nil
                }
                Button("Discard", role: .destructive) {
                    NewTaskDraftStore.clear()
                    pendingDraft = nil
                }
                Button("Keep Editing Later", role: .cancel) {
                    pendingDraft = nil
                }
            } message: { draft in
                Text(resumePromptMessage(for: draft))
            }
            .alert("Send voice note to AI?", isPresented: $isShowingVoiceTranscriptDisclosure) {
                Button("Not now", role: .cancel) { }
                Button("Allow") {
                    voiceTranscriptDisclosureShown = true
                    Task { await enhanceVoiceDraftWithAI() }
                }
            } message: {
                Text("To turn your voice note into a structured task, the transcript is sent to Anthropic's Claude API. Avoid speaking sensitive details (full names, addresses, ID numbers, medical info) you don't want to leave the device.")
            }
        }
    }

    private func resumePromptMessage(for draft: NewTaskDraft) -> String {
        let trimmedTitle = draft.title.trimmingCharacters(in: .whitespacesAndNewlines)
        let preview: String
        if !trimmedTitle.isEmpty {
            preview = "\"\(trimmedTitle)\""
        } else if !draft.voiceTranscript.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            preview = "your voice note"
        } else {
            preview = "your unfinished task"
        }
        let relative = draft.savedAt.formatted(.relative(presentation: .named))
        return "You have an unsaved task (\(preview)) from \(relative). Pick up where you left off?"
    }

    private func sanitizedAdvancedFields() -> [String: String] {
        let allowedKeys = Set(selectedCategory.advancedFields.map(\.rawValue))
        var result: [String: String] = [:]
        for (key, value) in form.advancedFieldValues where allowedKeys.contains(key) {
            let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty { result[key] = trimmed }
        }
        return result
    }

    private func currentDraftSnapshot() -> NewTaskDraft {
        NewTaskDraft(
            title: form.title,
            notes: form.notes,
            categoryRawValue: form.categoryRawValue,
            dueDate: form.dueDate,
            priorityRawValue: form.priority.rawValue,
            recurrenceRawValue: form.recurrence.rawValue,
            templateActionRawValue: form.templateAction.rawValue,
            durationMinutes: form.durationMinutes,
            voiceTranscript: form.voiceTranscript,
            locationName: form.locationConfig?.name,
            locationLatitude: form.locationConfig?.latitude,
            locationLongitude: form.locationConfig?.longitude,
            locationRadius: form.locationConfig?.radius,
            locationOnArrival: form.locationConfig?.onArrival,
            advancedFields: sanitizedAdvancedFields(),
            financialEnabled: form.financialEnabled,
            financialTypeRawValue: form.financialType.rawValue,
            plannedAmountText: form.plannedAmountText,
            actualAmountText: form.actualAmountText,
            currencyCode: form.currencyCode,
            budgetCategory: form.budgetCategory,
            hasPaymentDate: form.hasPaymentDate,
            paymentDate: form.hasPaymentDate ? form.paymentDate : nil,
            financialLinkRawValue: form.financialLinkOption.rawValue,
            financialNotes: form.financialNotes,
            includeInMonthlySpending: form.includeInMonthlySpending,
            markPlannedOnCreate: form.markPlannedOnCreate,
            savedAt: Date()
        )
    }

    private func draftHasContent() -> Bool {
        if !form.title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return true }
        if !form.notes.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return true }
        if !form.voiceTranscript.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return true }
        if form.locationConfig != nil { return true }
        if form.priority != .normal { return true }
        if form.recurrence != .none { return true }
        if !sanitizedAdvancedFields().isEmpty { return true }
        if form.financialEnabled { return true }
        return false
    }

    private func persistDraftIfMeaningful() {
        guard draftHasContent() else {
            NewTaskDraftStore.clear()
            return
        }
        NewTaskDraftStore.save(currentDraftSnapshot())
    }

    private func apply(draft: NewTaskDraft) {
        form.title = draft.title
        form.notes = draft.notes
        form.categoryRawValue = draft.categoryRawValue
        form.dueDate = draft.dueDate
        form.priority = TaskPriority(rawValue: draft.priorityRawValue) ?? .normal
        form.recurrence = TaskRecurrence(rawValue: draft.recurrenceRawValue) ?? .none
        form.templateAction = TaskTemplateAction(rawValue: draft.templateActionRawValue) ?? .none
        form.durationMinutes = draft.durationMinutes
        form.voiceTranscript = draft.voiceTranscript
        if let name = draft.locationName,
           let lat = draft.locationLatitude,
           let lon = draft.locationLongitude {
            form.locationConfig = LocationReminderConfig(
                name: name,
                latitude: lat,
                longitude: lon,
                radius: draft.locationRadius ?? 150,
                onArrival: draft.locationOnArrival ?? true
            )
        }
        form.advancedFieldValues = draft.advancedFields
        isAdvancedExpanded = !draft.advancedFields.isEmpty
        form.financialEnabled = draft.financialEnabled ?? false
        form.financialType = TaskFinancialType(rawValue: draft.financialTypeRawValue ?? "") ?? .expense
        form.plannedAmountText = draft.plannedAmountText ?? ""
        form.actualAmountText = draft.actualAmountText ?? ""
        form.currencyCode = MoneyCurrency.normalized(draft.currencyCode ?? MoneyCurrency.defaultCode)
        form.budgetCategory = draft.budgetCategory ?? ""
        form.hasPaymentDate = draft.hasPaymentDate ?? false
        form.paymentDate = draft.paymentDate ?? form.dueDate
        form.financialLinkOption = MoneyLinkOption(rawValue: draft.financialLinkRawValue ?? "") ?? .none
        form.financialNotes = draft.financialNotes ?? ""
        form.includeInMonthlySpending = draft.includeInMonthlySpending ?? true
        form.markPlannedOnCreate = draft.markPlannedOnCreate ?? false
    }

    private var header: some View {
        HStack(alignment: .firstTextBaseline, spacing: 6) {
            Text(existingTask == nil ? "New Task" : "Edit Task")
                .font(.lifeTrack(.title, weight: .bold))
                .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

            InfoTipButton(
                message: existingTask == nil
                    ? "Capture the next step with enough context to act on it."
                    : "Refine the details and keep reminders accurate."
            )

            Spacer(minLength: 0)
        }
    }

    private var taskCard: some View {
        SectionCardView {
            SectionHeaderView(
                title: "Task Details",
                infoMessage: "Name it clearly and classify it."
            )

            VStack(alignment: .leading, spacing: 7) {
                Text("Title")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                ZStack(alignment: .leading) {
                    if form.title.isEmpty {
                        Text("e.g. Send quarterly insurance update")
                            .font(.title3.weight(.semibold))
                            .foregroundStyle(LifeTrackTheme.ColorPalette.placeholderText)
                            .padding(.horizontal, 14)
                            .allowsHitTesting(false)
                    }

                    TextField("", text: $form.title)
                        .font(.title3.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                        .textInputAutocapitalization(.sentences)
                        .padding(13)
                }
                .background(LifeTrackTheme.ColorPalette.backgroundTop, in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
                .overlay {
                    RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                        .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.9), lineWidth: 0.8)
                }
            }

            VStack(alignment: .leading, spacing: 8) {
                Text("Category")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                LazyVGrid(
                    columns: [GridItem(.adaptive(minimum: 92), spacing: 8, alignment: .leading)],
                    alignment: .leading,
                    spacing: 8
                ) {
                    ForEach(categoryOptions) { option in
                        Button {
                            form.categoryRawValue = option.id
                            pendingCategoryOption = nil
                        } label: {
                            CategoryChipView(option: option, isSelected: form.categoryRawValue == option.id)
                        }
                        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                    }
                }

                Button {
                    isShowingCategoryManager = true
                } label: {
                    HStack(spacing: 8) {
                        Image(systemName: "plus")
                        Text("Custom category")
                    }
                    .font(.footnote.weight(.semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Capsule())
                }
                .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.96))
            }
        }
    }

    private var voiceCard: some View {
        VoiceInputCard(
            transcript: $form.voiceTranscript,
            isRecording: voiceInput.isRecording,
            audioLevel: voiceInput.audioLevel,
            feedbackMessage: voiceInput.feedbackMessage,
            authorizationMessage: voiceInput.authorizationMessage,
            isEnhancing: isAIEnhancing,
            onToggleRecording: { voiceInput.toggleRecording() },
            onApplyTranscript: { applyVoiceTranscript(form.voiceTranscript, force: true) },
            onClearTranscript: {
                voiceInput.clearTranscript()
                form.voiceTranscript = ""
                isAIEnhancing = false
            }
        )
    }

    private var planningCard: some View {
        SectionCardView {
            SectionHeaderView(
                title: "Planning",
                infoMessage: "Help LifeTrack choose what matters today."
            )

            VStack(alignment: .leading, spacing: 8) {
                Text("Priority")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                HStack(spacing: 8) {
                    ForEach(TaskPriority.allCases) { option in
                        Button {
                            form.priority = option
                        } label: {
                            PriorityPillView(priority: option, isSelected: form.priority == option)
                        }
                        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                    }
                }
            }

            VStack(alignment: .leading, spacing: 8) {
                Text("Repeat")
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)

                LazyVGrid(
                    columns: [GridItem(.adaptive(minimum: 92), spacing: 8, alignment: .leading)],
                    alignment: .leading,
                    spacing: 8
                ) {
                    ForEach(TaskRecurrence.allCases) { option in
                        Button {
                            form.recurrence = option
                        } label: {
                            RecurrencePillView(recurrence: option, isSelected: form.recurrence == option)
                        }
                        .buttonStyle(LifeTrackPressableButtonStyle(scale: 0.95, pressedOpacity: 0.92))
                    }
                }
            }
        }
    }

    private var financialDetailsCard: some View {
        TaskFinancialDetailsSection(
            isEnabled: $form.financialEnabled,
            financialType: $form.financialType,
            plannedAmountText: $form.plannedAmountText,
            actualAmountText: $form.actualAmountText,
            currencyCode: $form.currencyCode,
            budgetCategory: $form.budgetCategory,
            hasPaymentDate: $form.hasPaymentDate,
            paymentDate: $form.paymentDate,
            linkOption: $form.financialLinkOption,
            notes: $form.financialNotes,
            includeInMonthlySpending: $form.includeInMonthlySpending,
            markPlannedOnCreate: $form.markPlannedOnCreate,
            existingTaskHasActivity: existingTask?.hasFinancialActivity ?? false
        )
    }

    private var advancedFieldsCard: some View {
        let fields = selectedCategory.advancedFields
        return Group {
            if !fields.isEmpty {
                SectionCardView {
                    HStack(alignment: .center, spacing: LifeTrackTheme.Spacing.medium) {
                        Button(action: toggleAdvancedExpansion) {
                            Text("Advanced")
                                .font(.headline.weight(.semibold))
                                .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
                        }
                        .buttonStyle(.plain)

                        InfoTipButton(message: "Extra \(selectedCategory.title.lowercased()) fields — optional.")

                        Spacer(minLength: 0)

                        Button(action: toggleAdvancedExpansion) {
                            HStack(spacing: 10) {
                                if !advancedFilledKeys.isEmpty {
                                    Text("\(advancedFilledKeys.count)")
                                        .font(.caption.weight(.bold))
                                        .foregroundStyle(.white)
                                        .padding(.horizontal, 8)
                                        .padding(.vertical, 3)
                                        .background(LifeTrackTheme.ColorPalette.accent, in: Capsule())
                                }

                                Image(systemName: isAdvancedExpanded ? "chevron.up" : "chevron.down")
                                    .font(.system(size: 13, weight: .bold))
                                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                            }
                        }
                        .buttonStyle(.plain)
                    }

                    if isAdvancedExpanded {
                        VStack(alignment: .leading, spacing: LifeTrackTheme.Spacing.medium) {
                            ForEach(fields) { field in
                                advancedFieldRow(for: field)
                            }
                        }
                        .padding(.top, LifeTrackTheme.Spacing.small)
                    }
                }
            }
        }
    }

    private var advancedFilledKeys: [String] {
        selectedCategory.advancedFields
            .map(\.rawValue)
            .filter { key in
                !(form.advancedFieldValues[key]?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true)
            }
    }

    private func toggleAdvancedExpansion() {
        withAnimation(.easeInOut(duration: 0.22)) {
            isAdvancedExpanded.toggle()
        }
    }

    private func handleFloatingVoiceButtonTap(scrollProxy: ScrollViewProxy) {
        if voiceInput.isRecording {
            voiceInput.toggleRecording()
            return
        }

        withAnimation(.easeOut(duration: 0.28)) {
            scrollProxy.scrollTo(NewTaskViewAnchor.voiceCard, anchor: .top)
        }

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.12) {
            if !voiceInput.isRecording {
                voiceInput.toggleRecording()
            }
        }
    }

    @ViewBuilder
    private func advancedFieldRow(for field: AdvancedTaskField) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 6) {
                Image(systemName: field.symbolName)
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                Text(field.title)
                    .font(.lifeTrackCaption)
                    .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
            }

            TextField(
                field.placeholder,
                text: Binding(
                    get: { form.advancedFieldValues[field.rawValue] ?? "" },
                    set: { form.advancedFieldValues[field.rawValue] = $0 }
                )
            )
            .font(.body)
            .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)
            .padding(.horizontal, 14)
            .padding(.vertical, 11)
            .background(
                LifeTrackTheme.ColorPalette.backgroundTop,
                in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
            )
            .overlay {
                RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous)
                    .stroke(LifeTrackTheme.ColorPalette.hairline.opacity(0.9), lineWidth: 0.8)
            }
        }
    }

    private var documentCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Document", subtitle: "Scan a document or attach a file stored locally with this task.")

            HStack(spacing: LifeTrackTheme.Spacing.small) {
                DocumentCaptureButton(
                    title: "Scan",
                    subtitle: "Use camera",
                    symbolName: "doc.viewfinder",
                    tint: LifeTrackTheme.ColorPalette.accent,
                    isAvailable: DocumentScanAvailability.isSupported
                ) {
                    isScanningDocument = true
                }

                DocumentCaptureButton(
                    title: "Attach",
                    subtitle: "From files",
                    symbolName: "paperclip",
                    tint: LifeTrackTheme.ColorPalette.success,
                    isAvailable: true
                ) {
                    isImportingDocument = true
                }
            }

            AttachmentButton(
                documentDisplayName: form.documentDisplayName,
                onAttach: { isImportingDocument = true },
                onRemove: form.documentDisplayName == nil ? nil : { removeDocument() }
            )

            if let documentError {
                Text(documentError)
                    .font(.footnote.weight(.medium))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.danger)
            }

            if isAnalyzingDocument {
                HStack(spacing: LifeTrackTheme.Spacing.small) {
                    ProgressView()
                        .tint(LifeTrackTheme.ColorPalette.accent)

                    Text("Reading document locally...")
                        .font(.footnote.weight(.medium))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }
                .padding(11)
                .background(LifeTrackTheme.ColorPalette.backgroundTop.opacity(0.86), in: RoundedRectangle(cornerRadius: LifeTrackTheme.Radius.control, style: .continuous))
            } else if hasDocumentAnalysis {
                DocumentIntelligenceView(
                    summary: form.documentAnalysisSummary,
                    suggestedTitle: form.documentSuggestedTitle,
                    suggestedDueDate: form.documentSuggestedDueDate,
                    keywords: form.documentKeywords,
                    extractedText: form.documentExtractedText,
                    hasApplied: didApplyDocumentSuggestion,
                    onApplySuggestion: applyDocumentSuggestion
                )
            }
        }
    }

    private var templateActionCard: some View {
        SectionCardView {
            SectionHeaderView(title: "Template Action", subtitle: "This shortcut stays attached to the task.")

            HStack(spacing: LifeTrackTheme.Spacing.medium) {
                Image(systemName: "envelope.badge")
                    .font(.system(size: 17, weight: .semibold))
                    .foregroundStyle(LifeTrackTheme.ColorPalette.accent)
                    .frame(width: LifeTrackTheme.IconSize.largeCircle, height: LifeTrackTheme.IconSize.largeCircle)
                    .background(LifeTrackTheme.ColorPalette.accentSoft, in: Circle())

                VStack(alignment: .leading, spacing: 4) {
                    Text("Email draft")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(LifeTrackTheme.ColorPalette.primaryText)

                    Text("Open a pre-filled email from the task detail screen.")
                        .font(.footnote)
                        .foregroundStyle(LifeTrackTheme.ColorPalette.secondaryText)
                }
            }
        }
    }

    private var canSave: Bool {
        !form.title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private var categoryOptions: [TaskCategoryOption] {
        TaskCategoryOption.all(customCategories: customCategories)
    }

    private var selectedCategoryOption: TaskCategoryOption {
        if let pendingCategoryOption, pendingCategoryOption.id == form.categoryRawValue {
            return pendingCategoryOption
        }

        return TaskCategoryOption.resolved(rawValue: form.categoryRawValue, customCategories: customCategories)
    }

    private func removeDocument() {
        if form.documentStorageName != originalDocumentStorageName {
            DocumentStore.delete(storageName: form.documentStorageName)
        }
        form.documentStorageName = nil
        form.documentDisplayName = nil
        clearDocumentAnalysis()

        if form.notes == lastAutoGeneratedDocumentNotes {
            form.notes = ""
        }
        lastAutoGeneratedDocumentNotes = ""
    }

    private func handleScanResult(_ result: Result<URL, Error>) {
        switch result {
        case .success(let url):
            defer { try? FileManager.default.removeItem(at: url) }

            do {
                let pendingDocumentStorageName = form.documentStorageName
                let storedDocument = try DocumentStore.saveSecurityScopedFile(from: url)
                if pendingDocumentStorageName != originalDocumentStorageName {
                    DocumentStore.delete(storageName: pendingDocumentStorageName)
                }
                form.documentStorageName = storedDocument.storageName
                form.documentDisplayName = storedDocument.displayName
                documentError = nil
                analyzeDocument(storageName: storedDocument.storageName, displayName: storedDocument.displayName)
                LifeTrackHaptics.lightImpact()
            } catch {
                documentError = "Scan could not be saved."
                isAnalyzingDocument = false
            }
        case .failure(let error):
            if case DocumentScannerView.ScanError.cancelled = error {
                return
            }
            documentError = "Scan could not be completed."
            isAnalyzingDocument = false
        }
    }

    private func handleDocumentImport(_ result: Result<[URL], Error>) {
        switch result {
        case .success(let urls):
            guard let url = urls.first else {
                return
            }

            do {
                let pendingDocumentStorageName = form.documentStorageName
                let storedDocument = try DocumentStore.saveSecurityScopedFile(from: url)
                if pendingDocumentStorageName != originalDocumentStorageName {
                    DocumentStore.delete(storageName: pendingDocumentStorageName)
                }
                form.documentStorageName = storedDocument.storageName
                form.documentDisplayName = storedDocument.displayName
                documentError = nil
                analyzeDocument(storageName: storedDocument.storageName, displayName: storedDocument.displayName)
            } catch {
                documentError = "Document could not be attached."
                isAnalyzingDocument = false
            }
        case .failure:
            documentError = "Document could not be attached."
            isAnalyzingDocument = false
        }
    }

    private func analyzeDocument(storageName: String, displayName: String) {
        guard let url = DocumentStore.url(for: storageName) else {
            clearDocumentAnalysis()
            documentError = "Document was attached, but could not be read yet."
            return
        }

        clearDocumentAnalysis()
        isAnalyzingDocument = true

        Task {
            let result = await DocumentAnalysisManager.analyze(url: url, displayName: displayName)
            await MainActor.run {
                guard form.documentStorageName == storageName else {
                    return
                }

                form.documentExtractedText = result.extractedText
                form.documentAnalysisSummary = result.summary
                form.documentSuggestedTitle = result.suggestedTitle
                form.documentSuggestedDueDate = result.suggestedDueDate
                form.documentKeywords = result.keywords
                isAnalyzingDocument = false

                applyAutoGeneratedDocumentNotes(displayName: displayName, result: result)
            }
        }
    }

    private func applyAutoGeneratedDocumentNotes(displayName: String, result: DocumentAnalysisResult) {
        let autoNotes = buildAutoDocumentNotes(displayName: displayName, result: result)
        guard !autoNotes.isEmpty else { return }

        let trimmed = form.notes.trimmingCharacters(in: .whitespacesAndNewlines)

        if trimmed.isEmpty || form.notes == lastAutoGeneratedDocumentNotes {
            form.notes = autoNotes
            lastAutoGeneratedDocumentNotes = autoNotes
        }
    }

    private func buildAutoDocumentNotes(displayName: String, result: DocumentAnalysisResult) -> String {
        var lines: [String] = ["Attached: \(displayName)"]

        if !result.keywords.isEmpty {
            lines.append("Detected: \(result.keywords.prefix(5).joined(separator: ", "))")
        }

        if let suggestedDueDate = result.suggestedDueDate {
            lines.append("Date found: \(suggestedDueDate.weekdayDateString)")
        }

        let excerpt = documentExcerpt(from: result.extractedText)
        if !excerpt.isEmpty {
            lines.append("")
            lines.append(excerpt)
        }

        return lines.joined(separator: "\n")
    }

    private func documentExcerpt(from text: String) -> String {
        let normalized = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else { return "" }

        let maxLength = 240
        if normalized.count <= maxLength {
            return normalized
        }

        let clipped = normalized.prefix(maxLength)
        if let lastSpace = clipped.lastIndex(of: " ") {
            return clipped[..<lastSpace] + "…"
        }

        return clipped + "…"
    }

    private func clearDocumentAnalysis() {
        form.documentExtractedText = ""
        form.documentAnalysisSummary = nil
        form.documentSuggestedTitle = nil
        form.documentSuggestedDueDate = nil
        form.documentKeywords = []
        didApplyDocumentSuggestion = false
    }

    private var hasDocumentAnalysis: Bool {
        form.documentAnalysisSummary != nil ||
            form.documentSuggestedTitle != nil ||
            form.documentSuggestedDueDate != nil ||
            !form.documentKeywords.isEmpty ||
            !form.documentExtractedText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func applyDocumentSuggestion() {
        var didChange = false

        if let suggestedTitle = form.documentSuggestedTitle, !suggestedTitle.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            withAnimation(.easeOut(duration: 0.2)) {
                form.title = suggestedTitle
            }
            didChange = true
        }

        if let suggestedDueDate = form.documentSuggestedDueDate {
            withAnimation(.easeOut(duration: 0.2)) {
                form.dueDate = suggestedDueDate
            }
            didChange = true
        }

        if form.documentKeywords.contains("insurance") || form.documentKeywords.contains("invoice") || form.documentKeywords.contains("bill") || form.documentKeywords.contains("tax") {
            form.categoryRawValue = TaskCategory.finance.rawValue
            pendingCategoryOption = nil
            didChange = true
        } else if form.documentKeywords.contains("appointment") || form.documentKeywords.contains("medical") {
            form.categoryRawValue = TaskCategory.health.rawValue
            pendingCategoryOption = nil
            didChange = true
        } else if form.documentKeywords.contains("school") || form.documentKeywords.contains("application") {
            form.categoryRawValue = TaskCategory.personal.rawValue
            pendingCategoryOption = nil
            didChange = true
        }

        if didChange {
            LifeTrackHaptics.lightImpact()
            withAnimation(.easeOut(duration: 0.22)) {
                didApplyDocumentSuggestion = true
            }
            documentScrollRequest = UUID()
        }
    }

    private func applyVoiceTranscript(_ transcript: String, force: Bool = false) {
        let cleanedTranscript = transcript.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleanedTranscript.isEmpty else {
            return
        }

        let draft = VoiceTaskParser.parse(cleanedTranscript)

        if let draftTitle = draft.title, force || form.title.isEmpty || form.title == lastVoiceGeneratedTitle {
            form.title = draftTitle
            lastVoiceGeneratedTitle = draftTitle
        }

        if let draftCategory = draft.category, force || !didApplyVoiceCategory {
            form.categoryRawValue = draftCategory.rawValue
            pendingCategoryOption = nil
            didApplyVoiceCategory = true
        }

        if let draftDueDate = draft.dueDate, force || !didApplyVoiceDueDate {
            form.dueDate = draftDueDate
            didApplyVoiceDueDate = true
        }

        let trimmedNotes = form.notes.trimmingCharacters(in: .whitespacesAndNewlines)
        let notesIsOverridableByVoice =
            trimmedNotes.isEmpty ||
            form.notes == lastVoiceGeneratedNotes ||
            (trimmedNotes == lastAutoGeneratedDocumentNotes.trimmingCharacters(in: .whitespacesAndNewlines) && !lastAutoGeneratedDocumentNotes.isEmpty)

        if let draftNotes = draft.notes, !draftNotes.isEmpty, force || notesIsOverridableByVoice {
            form.notes = draftNotes
            lastVoiceGeneratedNotes = draftNotes
        } else if draft.notes == nil, form.notes == lastVoiceGeneratedNotes, !lastVoiceGeneratedNotes.isEmpty {
            form.notes = ""
            lastVoiceGeneratedNotes = ""
        }

        if let draftPriority = draft.priority, force {
            form.priority = draftPriority
        }

        applyFinancialDraft(draft, force: force)
    }

    private func applyFinancialDraft(_ draft: VoiceTaskDraft, force: Bool) {
        let hasFinancialValues =
            draft.financialEnabled == true ||
            draft.financialType != nil ||
            draft.plannedAmount != nil ||
            draft.actualAmount != nil ||
            draft.currencyCode != nil ||
            draft.budgetCategory != nil ||
            draft.paymentDate != nil ||
            draft.linkedBudgetId != nil ||
            draft.linkedGoalId != nil ||
            draft.includeInMonthlySpending != nil ||
            draft.markPlannedOnCreate != nil ||
            draft.financialNotes != nil

        guard hasFinancialValues else { return }

        let wasFinancialEnabled = form.financialEnabled
        if force || !form.financialEnabled || draft.financialEnabled == true {
            form.financialEnabled = true
        }

        if let draftType = draft.financialType, force || !wasFinancialEnabled {
            form.financialType = draftType
        }

        if let plannedAmount = draft.plannedAmount,
           force || form.plannedAmountText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            form.plannedAmountText = Self.amountInputString(plannedAmount)
        }

        if let actualAmount = draft.actualAmount,
           force || form.actualAmountText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            form.actualAmountText = Self.amountInputString(actualAmount)
        }

        if draft.currencyCode != nil,
           force || form.currencyCode == MoneyCurrency.defaultCode {
            form.currencyCode = Self.currentMoneyCurrencyCode
        }

        if let draftBudgetCategory = draft.budgetCategory,
           force || form.budgetCategory.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            form.budgetCategory = draftBudgetCategory
        }

        if let draftPaymentDate = draft.paymentDate, force || !form.hasPaymentDate {
            form.paymentDate = draftPaymentDate
            form.hasPaymentDate = true
        }

        if (draft.linkedBudgetId != nil || draft.linkedGoalId != nil), force || !wasFinancialEnabled {
            form.financialLinkOption = MoneyLinkOption.resolved(
                budgetId: draft.linkedBudgetId,
                goalId: draft.linkedGoalId
            )
        }

        if let include = draft.includeInMonthlySpending, force || !wasFinancialEnabled {
            form.includeInMonthlySpending = include
        }

        if let markPlanned = draft.markPlannedOnCreate, force || !wasFinancialEnabled {
            form.markPlannedOnCreate = markPlanned
        }

        if let draftNotes = draft.financialNotes,
           force || form.financialNotes.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            form.financialNotes = draftNotes
        }
    }

    private func enhanceVoiceDraftWithAI() async {
        if !voiceTranscriptDisclosureShown {
            await MainActor.run { isShowingVoiceTranscriptDisclosure = true }
            return
        }

        isAIEnhancing = true
        defer { isAIEnhancing = false }

        guard let enhanced = await voiceEnhancer.enhance(transcript: form.voiceTranscript) else { return }

        withAnimation(.easeOut(duration: 0.22)) {
            applyVoiceTranscript(form.voiceTranscript, force: false)

            if let t = enhanced.title, !t.isEmpty {
                form.title = t
                lastVoiceGeneratedTitle = t
            }

            if let n = enhanced.notes, !n.isEmpty {
                form.notes = n
                lastVoiceGeneratedNotes = n
            }

            if let d = enhanced.dueDate {
                form.dueDate = d
                didApplyVoiceDueDate = true
            }

            if let cat = enhanced.category {
                form.categoryRawValue = cat.rawValue
                didApplyVoiceCategory = true
            }

            if let pri = enhanced.priority {
                form.priority = pri
            }

            if !enhanced.advancedFields.isEmpty {
                let allowedKeys = Set(selectedCategory.advancedFields.map(\.rawValue))
                for (key, value) in enhanced.advancedFields where allowedKeys.contains(key) {
                    let existing = form.advancedFieldValues[key]?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
                    if existing.isEmpty {
                        form.advancedFieldValues[key] = value
                    }
                }
                if !form.advancedFieldValues.isEmpty {
                    isAdvancedExpanded = true
                }
            }

            applyFinancialDraft(enhanced, force: false)
        }
    }

    private func save() {
        let cleanedTitle = form.title.trimmingCharacters(in: .whitespacesAndNewlines)
        let now = Date()
        let wasCompleted = existingTask?.isCompleted ?? false

        let task: LifeTask
        if let existingTask {
            task = existingTask
            if originalDocumentStorageName != form.documentStorageName {
                DocumentStore.delete(storageName: originalDocumentStorageName)
            }
            task.title = cleanedTitle
            task.categoryRawValue = form.categoryRawValue
            task.dueDate = form.dueDate
            task.isCompleted = form.isCompleted
            task.notes = form.notes
            task.templateAction = form.templateAction
            task.priority = form.priority
            task.recurrence = form.recurrence
            task.scheduledDurationMinutes = form.durationMinutes
            task.documentStorageName = form.documentStorageName
            task.documentDisplayName = form.documentDisplayName
            task.documentExtractedText = form.documentExtractedText
            task.documentAnalysisSummary = form.documentAnalysisSummary
            task.documentSuggestedTitle = form.documentSuggestedTitle
            task.documentSuggestedDueDate = form.documentSuggestedDueDate
            task.documentKeywords = form.documentKeywords
            task.locationReminderName = form.locationConfig?.name
            task.locationReminderLatitude = form.locationConfig?.latitude
            task.locationReminderLongitude = form.locationConfig?.longitude
            task.locationReminderRadius = form.locationConfig?.radius
            task.locationReminderOnArrival = form.locationConfig?.onArrival ?? true
            task.advancedFields = sanitizedAdvancedFields()
            applyFinancialDetails(to: task)
            task.updatedAt = now
        } else {
            task = LifeTask(
                title: cleanedTitle,
                category: selectedCategory,
                categoryRawValue: form.categoryRawValue,
                dueDate: form.dueDate,
                isCompleted: form.isCompleted,
                notes: form.notes,
                templateAction: form.templateAction,
                priority: form.priority,
                recurrence: form.recurrence,
                estimatedDurationMinutes: form.durationMinutes,
                documentStorageName: form.documentStorageName,
                documentDisplayName: form.documentDisplayName,
                documentExtractedText: form.documentExtractedText,
                documentAnalysisSummary: form.documentAnalysisSummary,
                documentSuggestedTitle: form.documentSuggestedTitle,
                documentSuggestedDueDate: form.documentSuggestedDueDate,
                documentKeywords: form.documentKeywords,
                createdAt: now,
                updatedAt: now
            )
            task.locationReminderName = form.locationConfig?.name
            task.locationReminderLatitude = form.locationConfig?.latitude
            task.locationReminderLongitude = form.locationConfig?.longitude
            task.locationReminderRadius = form.locationConfig?.radius
            task.locationReminderOnArrival = form.locationConfig?.onArrival ?? true
            task.advancedFields = sanitizedAdvancedFields()
            applyFinancialDetails(to: task)
            if task.isHabit { task.habitGroupID = task.id }
            modelContext.insert(task)
        }

        let nextRecurringTask: LifeTask?
        if !wasCompleted && task.isCompleted {
            nextRecurringTask = task.nextRecurringTask(completedAt: now)
            if let nextRecurringTask {
                modelContext.insert(nextRecurringTask)
            }
        } else {
            nextRecurringTask = nil
        }

        try? modelContext.save()
        ReminderScheduler.synchronizeReminder(
            taskID: task.id,
            title: task.title,
            categoryTitle: selectedCategoryOption.title,
            dueDate: task.dueDate,
            isCompleted: task.isCompleted,
            isHighPriority: task.priority == .high,
            detailLine: task.reminderDetailLine(categoryTitle: selectedCategoryOption.title)
        )
        if let nextRecurringTask {
            TaskLifecycleManager.synchronizeReminder(
                for: nextRecurringTask,
                customCategories: customCategories
            )
        }
        LocationReminderManager.shared.cancelRegion(for: task.id)
        if task.hasLocationReminder && !task.isCompleted {
            LocationReminderManager.shared.scheduleRegion(for: task)
        }
        didSave = true
        if isFreshNewTask {
            NewTaskDraftStore.clear()
        }
        dismiss()
    }

    private func applyFinancialDetails(to task: LifeTask) {
        task.financialEnabled = form.financialEnabled
        task.financialType = form.financialType
        task.plannedAmount = form.financialEnabled ? parseAmount(form.plannedAmountText) : 0
        let actual = parseAmount(form.actualAmountText)
        task.actualAmount = form.financialEnabled && actual > 0 ? actual : nil
        task.currencyCode = MoneyCurrency.normalized(form.currencyCode)
        task.budgetCategory = form.financialEnabled ? form.budgetCategory.trimmingCharacters(in: .whitespacesAndNewlines) : ""
        task.paymentDate = form.financialEnabled && form.hasPaymentDate ? form.paymentDate : nil
        task.linkedBudgetId = form.financialEnabled ? form.financialLinkOption.budgetId : nil
        task.linkedGoalId = form.financialEnabled ? form.financialLinkOption.goalId : nil
        task.includeInMonthlySpending = form.includeInMonthlySpending
        task.markPlannedOnCreate = form.markPlannedOnCreate
        task.financialNotes = form.financialEnabled ? form.financialNotes : ""
    }

    private func parseAmount(_ value: String) -> Double {
        let normalized = value
            .replacingOccurrences(of: ",", with: ".")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return Double(normalized) ?? 0
    }

    private static func amountInputString(_ amount: Double?) -> String {
        guard let amount, amount > 0 else { return "" }
        if amount.rounded(.down) == amount {
            return String(Int(amount))
        }
        return String(format: "%.2f", amount)
    }

    private var selectedCategory: TaskCategory {
        TaskCategory(rawValue: form.categoryRawValue) ?? .other
    }

}

private enum NewTaskViewAnchor: Hashable {
    case voiceCard
    case taskCard
}

#Preview("New Task") {
    let configuration = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(for: LifeTask.self, CustomTaskCategory.self, configurations: configuration)

    return NewTaskView(template: TaskTemplate.common.first)
        .modelContainer(container)
}
